### ISSUE TITLE
Huge performance degradation introduced with @react-email/components 0.0.8 and higher 🐢

### ISSUE THREAD

**Issue by nikita-resh** [resendlabs/react-email#1016]
### Describe the Bug

Context: I'm developing an AWS Lambda with SES and react-email, so execution time is critical. After upgrading @react-email/components to 0.0.8 or higher, the average execution time has increased tenfold.

To emulate an environment with limited resources, I ran my lambda in a Docker container with memory and CPU settings configured in docker-compose.yml.

Findings:
- The issue seems related to how @react-email/components handles Tailwind styles.
- The more Tailwind styles you incorporate, the more noticeable the performance degradation.

Below are some performance measurements. ([code base can be found here](https://github.com/nikita-resh/react-email-performance-issue)):

0.0.7
<img width="831" alt="0 0 7" src="https://github.com/resendlabs/react-email/assets/73827665/1de11ef0-5417-406a-8f17-c0677eaac82a">

0.0.7 + tailwind (+31 % to execution time which is totally fine)
<img width="831" alt="0 0 7 + tailwind" src="https://github.com/resendlabs/react-email/assets/73827665/362cf064-cb4d-4262-924b-8aeb89fb4a41">

0.0.11
<img width="1122" alt="0 0 11" src="https://github.com/resendlabs/react-email/assets/73827665/3e3f206e-c2fc-4d14-afad-48195445a525">

0.0.11 + tailwind (+11k % to execution time 🐢)
<img width="831" alt="0 0 11 + tailwind" src="https://github.com/resendlabs/react-email/assets/73827665/75728fa0-4d9b-40d0-9377-ffc5ddbdae68">

### Which package is affected (leave empty if unsure)

@react-email/components

### Link to the code that reproduces this issue

https://github.com/nikita-resh/react-email-performance-issue

### To Reproduce

Pre-requirements: 
- docker installed

I've prepared a public [GitHub repo](https://github.com/nikita-resh/react-email-performance-issue) with everything needed to reproduce the issue. You can find four commits in the main branch corresponding to each state from the attached images.

Here's how you can measure execution time on your own:

1. Checkout commit with
2. Execute `docker-compose build --no-cache` in root folder
3. Execute `docker-compose up` in root folder
4. Find `performance-issue-container  | EXECUTION: <x>s` in logs

Note: don't forget to add `--no-cache` flag after checkout a different commit

### Expected Behavior

Expect that the execution time will not increase after upgrading to @react-email/components 0.0.8 or higher.

### What's your node version? (if relevant)

18.17.1

**Comment by gabrielmfern** [comment]
Yeah, this is something we are aware of. The Tailwind component is pretty slow atm and we are planning some perf improvements soon.

**Comment by sysmat** [comment]
- tailwindcss > 3 is very fast, I used it with vite it works like a charm
- there are warning in react(React does not recognize the `pX`, `pY`,.... prop on a DOM element)
- there are errors in browser (hydration-error-info.js:27 )

**Comment by sysmat** [comment]
I do some experiments and upgrade .react-email

```
@radix-ui/colors                0.1.8  →    3.0.0
 @radix-ui/react-collapsible     1.0.1  →    1.0.3
 @radix-ui/react-popover         1.0.2  →    1.0.7
 @radix-ui/react-slot            1.0.1  →    1.0.2
 @radix-ui/react-toggle-group    1.0.1  →    1.0.4
 @radix-ui/react-tooltip         1.0.2  →    1.0.7
 @react-email/render             0.0.7  →    0.0.9
 @types/node                   18.11.9  →  20.8.10
 @types/react                  18.0.25  →  18.2.34
 @types/react-dom               18.0.9  →  18.2.14
 autoprefixer                  10.4.13  →  10.4.16
 eslint                         8.36.0  →   8.53.0
 eslint-config-next             13.2.4  →   14.0.1
 eslint-config-prettier          8.7.0  →    9.0.0
 eslint-plugin-unused-imports    2.0.0  →    3.0.0
 framer-motion                   8.4.6  →  10.16.4
 next                           13.2.4  →   14.0.1
 postcss                        8.4.19  →   8.4.31
 prettier                        2.8.4  →    3.0.3
 prism-react-renderer            1.3.5  →    2.1.0
 tailwindcss                     3.2.4  →    3.3.5
 typescript                      4.9.3  →    5.2.2
```

- after upgrade it start working much faster, so no problem with tailwindcss 
- with next  14 there are depricated config and errors(ttempted import error: 'prism-react-renderer' does not contain a default export (imported as 'Highlight'), Attempted import error: 'prism-react-renderer' does not contain a default export (imported as 'Highlight').) but app is working 100x faster

**Comment by sysmat** [comment]
- hm after upgrading it is still a huge performance problem, a little better but still huge degradation

**Comment by sysmat** [comment]
```
 Generating emails preview(node:24721) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

**Comment by sysmat** [comment]
"@react-email/components": "0.0.7", is still best performance

**Comment by viperxeyes** [comment]
Because of this performance issue , the render function takes long time to execute and on Vercel , the max duration on a hobby plan is 10 sec , and this results in 504 error being thrown while taking long time to render to html

**Comment by gabrielmfern** [comment]
> Because of this performance issue , the render function takes long time to execute and on Vercel , the max duration on a hobby plan is 10 sec , and this results in 504 error being thrown while taking long time to render to html

Yeah, as I said before, on environments that you want this to run fast, best case scenario is you pre-render the HTML and send it. But besides this somewhat of a workaround, I am working on some perf improvements to the component right now.

**Comment by bukinoshita** [comment]
We released a `@react-email/tailwind@0.0.13-canary.1` that should fix that issue. You can install the `@react-email/components@0.0.12-canary.0` as well. Please, let me know if the performance issue still persist

**Comment by bodinsamuel** [comment]
Hey, 
tried to use the canary version but got this error. I guess it's because I use `type: module`, can you advice?



```ts
file:///node_modules/@react-email/tailwind/dist/index.mjs:78594
     var _fs = /* @__PURE__ */ _interop_require_default(__require("fs"));
                                                       ^
 Error: Dynamic require of "fs" is not supported
     at file:///node_modules/@react-email/tailwind/dist/index.mjs:12:9
```

> you should render the HTML only once and not every time the function runs to get the best performance possible.

As a side note, there is no tutorial on how to achieve that, especially on monorepo. `emails exports` only output the raw code without types and does not follow `tsconfig.json` which creates incompatibilities. 
Right now to compile react-email I already need a two step compilation `tsc -p tsconfig.json && tsup` that is not working well with turbo repo.

**Comment by gabrielmfern** [comment]
> Hey, tried to use the canary version but got this error. I guess it's because I use `type: module`, can you advice?
> 
> ```ts
> file:///node_modules/@react-email/tailwind/dist/index.mjs:78594
>      var _fs = /* @__PURE__ */ _interop_require_default(__require("fs"));
>                                                        ^
>  Error: Dynamic require of "fs" is not supported
>      at file:///node_modules/@react-email/tailwind/dist/index.mjs:12:9
> ```
> 
> > you should render the HTML only once and not every time the function runs to get the best performance possible.
> 
> As a side note, there is no tutorial on how to achieve that, especially on monorepo. `emails exports` only output the raw code without types and does not follow `tsconfig.json` which creates incompatibilities. Right now to compile react-email I already need a two step compilation `tsc -p tsconfig.json && tsup` that is not working well with turbo repo.

Can you try out `@react-email/tailwind@0.0.13-dev.user-build-problems.0`?

--- 

`email export` should generate HTML files that you can use directly when sending the email, if it generates js files it means there was an error and the export command gives some shallow feedback
Also, are you compiling react-email yourself I couldn't follow?

**Comment by bodinsamuel** [comment]
> Can you try out @react-email/tailwind@0.0.13-dev.user-build-problems.0?

Yes, seems to fix the issue thanks !

**Comment by sandercoffee** [comment]
Remains extremely slow!

How do I best use with next.js in Vercel?
just running next build in my project, the emails is compiled every time each request.

How should I use export and import later when I need to use it?

**Comment by gabrielmfern** [comment]
@sandercoffee Couldn't follow the last part, what do you mean by "export and import later"?
