### ISSUE TITLE
TypeError after upgrading `@types/react` to `18.2.34`, while `18.2.21` works fine

### ISSUE THREAD

**Issue by MartinXPN** [resendlabs/react-email#1020]
### Describe the Bug

Typescript throws an error of `<Html>` and all the other components cannot be part of `JSX` after upgrading the  `@types/react` to `18.2.34`. The previous version where the types were set to the version `18.2.21` worked fine.

### Which package is affected (leave empty if unsure)

@react-email/components, react-email

### Link to the code that reproduces this issue

https://github.com/MartinXPN/nextjs-firebase-mui-starter/blob/main/functions/package.json#L41C31-L41C31

### To Reproduce

Upgrade the package and you'll get the type errors.

### Expected Behavior

We should not have those type errors

### What's your node version? (if relevant)

18

**Comment by gabrielmfern** [comment]
Yeah this is as usual with react libraries, only when we update the @types/react for react-email that this will go away. Do you have any specific reasons to upgrade to the new types? Generally, if you upgrade and the library doesn't you'll get errors like these.

**Comment by MartinXPN** [comment]
Thanks for the quick response @gabrielmfern . No urgent reason tbh - just trying to keep all the library versions as close to the latest as possible.

**Comment by gabrielmfern** [comment]
> Thanks for the quick response @gabrielmfern . No urgent reason tbh - just trying to keep all the library versions as close to the latest as possible.

Maybe try keeping the versions for @types/react the same as react-emails's and when there is a new release out you can upgrade. Do you have any more questions or is it okay if I close this issue?

**Comment by MartinXPN** [comment]
No more questions. Thanks!
I think it's okay to close the issue.
