### ISSUE TITLE
Latest update won't output tailwind classes to <head>

### ISSUE THREAD

**Issue by eivindml** [resendlabs/react-email#1053]
### Describe the Bug

After updating all my `@react-email` packages to their latest version, it won't render the content correctly.

What's happening is that it looks like the Tailwind component stops outputting it's generated CSS for the utility classes I use.

With old version there are 5 <script> tags generated, where the 5th one contains the css utility classes generated by Tailwind. When updating, only 4 script tags are present (all custom fonts), but no css i generated, and that breaks the layout.

Screenshots:

Old version
<img width="1571" alt="Skjermbilde 2023-11-27 kl  13 23 26" src="https://github.com/resendlabs/react-email/assets/202450/a3bf62fb-3083-49cb-9032-6c1763b8fff2">

Latest version
<img width="681" alt="Skjermbilde 2023-11-27 kl  13 23 51" src="https://github.com/resendlabs/react-email/assets/202450/22108537-3803-4943-a27c-3e06b4d8ecfe">

These are the working packages:
```
    "@react-email/components": "^0.0.7",
    "@react-email/font": "^0.0.3",
    "@react-email/render": "^0.0.7",
    "@react-email/tailwind": "^0.0.8",
```

These are not working:
```
   "@react-email/components": "^0.0.11",
    "@react-email/font": "^0.0.4",
    "@react-email/render": "^0.0.9",
    "@react-email/tailwind": "^0.0.12",
```

### Link to the code that reproduces this issue

n/a

### To Reproduce

Update all to latest, use css classes, and check the outputted html.

### Expected Behavior

It to generate css classes.

**Comment by zenorocha** [comment]
Can you try using the latest canary for the Tailwind package [0.0.13-canary.3](https://www.npmjs.com/package/@react-email/tailwind/v/0.0.13-canary.3)?

**Comment by eivindml** [comment]
The only way for me to get it to work now is to downgrade, and then also downgrade next@14 to next@13 (related: https://github.com/resendlabs/react-email/issues/1029)

**Comment by gabrielmfern** [comment]
Are the styles not getting inlined on your template with the latest canary?

**Comment by eivindml** [comment]
> Hey @eivindml, are the styles not getting inlined on your template with the latest canary?
> 
> Also since you are using the components package as well, did you make sure you imported from `@react-email/tailwind` instead of `@react-email/components` for testing?
> 
> Styles should be inlined because the support on email clients will be better with inlined styles rather than defined on the <style> tag. The only place left to have classes being kept is when you use media queries since there is no other way to apply the styles otherwise.

Styles are being inlined. That part works. It's just the generation of the `<script>` tag for responsive layout stuff. 

---

You where right, I was importing `Tailwind` from `@react-email/components`. I've fixed that now. Unfortunately, that wasn't enough. Updating to `"@react-email/tailwind": "0.0.13-canary.3"` breaks my project (Sanity Studio, react-based). 

I tried to use all different `canary` packages to see where it breaks.

* `@react-email/tailwind@0.0.13-canary.0` – Project builds, but won't generate `<script>` tag for media queries.
* `@react-email/tailwind@0.0.13-canary.1` – Gives build error for project: `Uncaught error: os.platform is not a function. (In 'os.platform()', 'os.platform' is undefined)` See screenshot
* `@react-email/tailwind@0.0.13-canary.2` – Gives build error for project: `Uncaught error: Dynamic require of "fs" is not supported`
* `@react-email/tailwind@0.0.13-canary.3` – Gives build error for project: `Uncaught error: Dynamic require of "fs" is not supported` See screenshot

<img width="1018" alt="Skjermbilde 2023-11-27 kl  15 38 01" src="https://github.com/resendlabs/react-email/assets/202450/e30dcf71-ec45-4b75-8211-bfda1cf65936">

<img width="1044" alt="Skjermbilde 2023-11-27 kl  15 37 34" src="https://github.com/resendlabs/react-email/assets/202450/14c339fb-5cac-47a8-9edd-8894158b21c1">

**Comment by eivindml** [comment]
Hmm, unfortunately I still get this error on `canary.4`. 

<img width="1037" alt="Skjermbilde 2023-11-27 kl  16 45 34" src="https://github.com/resendlabs/react-email/assets/202450/c14036fa-7e64-461b-aa4c-9600e794d5ad">

**Comment by jwarykowski** [comment]
@gabrielmfern - just to note I can see the same issue on my project using the following versions:

```
"@react-email/components": "^0.0.11",
"@react-email/render": "^0.0.9",
"@react-email/tailwind": "0.0.13-canary.4"
```

Note I need to add the following to get around the `Failed to compile Error: ReactServerComponentsError ./src/app/preview/[slug]/page.tsx` [issue](https://github.com/resendlabs/react-email/issues/1041#issuecomment-1821901988). 

```
experimental: {
   serverComponentsExternalPackages: [
     '@react-email/components',
     '@react-email/render',
     '@react-email/tailwind'
   ]
 }
 ```
 
 Furthermore, I must wrap the `<Tailwind>` component directly around `<Head>`, previously this was not required, can you confirm this is intentional? 
 
 ```
 <Tailwind config={config}>
  <Head>
    ...
  </Head>
</Tailwind>
```

**Comment by gabrielmfern** [comment]
> @gabrielmfern - just to note I can see the same issue on my project using the following versions:
> 
> ```
> "@react-email/components": "^0.0.11",
> "@react-email/render": "^0.0.9",
> "@react-email/tailwind": "0.0.13-canary.4"
> ```
> 
> Note I need to add the following to get around the `Failed to compile Error: ReactServerComponentsError ./src/app/preview/[slug]/page.tsx` [issue](https://github.com/resendlabs/react-email/issues/1041#issuecomment-1821901988).
> 
> ```
> experimental: {
>    serverComponentsExternalPackages: [
>      '@react-email/components',
>      '@react-email/render',
>      '@react-email/tailwind'
>    ]
>  }
> ```
> 
> Furthermore, I must wrap the `<Tailwind>` component directly around `<Head>`, previously this was not required, can you confirm this is intentional?
> 
> ```
> <Tailwind config={config}>
>  <Head>
>    ...
>  </Head>
> </Tailwind>
> ```

Having to wrap it like this is intentional, at least for now, it makes the underlying code simpler. 
Is your issue that the media queries are not appearing as well? If so, can you show me some minimal email with that issue so I can track it down?

**Comment by gabrielmfern** [comment]
> Hmm, unfortunately I still get this error on `canary.4`.
> <img alt="Skjermbilde 2023-11-27 kl 16 45 34" width="1037" src="https://private-user-images.githubusercontent.com/202450/285928252-c14036fa-7e64-461b-aa4c-9600e794d5ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjk5ODYsIm5iZiI6MTcwMTI2OTY4NiwicGF0aCI6Ii8yMDI0NTAvMjg1OTI4MjUyLWMxNDAzNmZhLTdlNjQtNDYxYi1hYTRjLTk2MDBlNzk0ZDVhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQxNDU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDk4MWI3MTQwZGY2ZWU4YzcwODc4MzYxNDAzMDE5Mzk5MWM5ZWRhZjgyODdhYzM0ZjVkZTJhNjViNjRmMDBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QbQvOctmpG4wMK6BPFsLRCTdGR2lOhInszLhgZaEuw8">

Been working on this for a bit, sorry for the delay, can you try out `@react-email/tailwind@0.0.13-dev.user-build-problems.0` for me?

**Comment by JaviEzpeleta** [comment]
> > Hmm, unfortunately I still get this error on `canary.4`.
> > <img alt="Skjermbilde 2023-11-27 kl 16 45 34" width="1037" src="https://private-user-images.githubusercontent.com/202450/285928252-c14036fa-7e64-461b-aa4c-9600e794d5ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjk5ODYsIm5iZiI6MTcwMTI2OTY4NiwicGF0aCI6Ii8yMDI0NTAvMjg1OTI4MjUyLWMxNDAzNmZhLTdlNjQtNDYxYi1hYTRjLTk2MDBlNzk0ZDVhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQxNDU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDk4MWI3MTQwZGY2ZWU4YzcwODc4MzYxNDAzMDE5Mzk5MWM5ZWRhZjgyODdhYzM0ZjVkZTJhNjViNjRmMDBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QbQvOctmpG4wMK6BPFsLRCTdGR2lOhInszLhgZaEuw8">
> 
> Been working on this for a bit, sorry for the delay, can you try out `@react-email/tailwind@0.0.13-dev.user-build-problems.0` for me?

It worked for me! 
🤩 
thank u so much!!!

**Comment by gabrielmfern** [comment]
We released a new version now stable that solves this `@react-email/tailwind@0.0.13`.

**Comment by jwarykowski** [comment]
Hey @gabrielmfern, thanks for the update and apologies for not getting back to you sooner. I've updated my project to the following versions but I'm still seeing issues unfortunately:

```
"dependencies": {
    "@react-email/components": "^0.0.12",
    "@react-email/render": "^0.0.10",
    "@react-email/tailwind": "0.0.13"
  }
```

![Screenshot 2023-12-04 at 08 33 33](https://github.com/resendlabs/react-email/assets/406799/6f4cabd5-dcad-4603-a4e6-1399775fdb13)

The first issue I see is that the `html-react-parser` package module is missing, upon adding this locally I then get the same issue but for the `tw-to-css` package. Once I've installed both locally I get the previous problem where the tailwind styles are not being applied as expected.

Note I've blown away my local `.react-email` directory and rebuilt to ensure a clean build but the same issue persists. Furthermore I've also attempted to import `Tailwind` directly (from the specific pacakge) and the `components` package but no joy.


 If possible can you confirm all of the versions that should be used and if you're able to link to a working example that would be great so that I can compare.

**Comment by gabrielmfern** [comment]
Hey @jwarykowski, these issues seem a lot like a problem on your environment (maybe the lockfile or outdated node_modules?) because `tw-to-css` is not a dependency of the Tailwind component anymore, same for `html-react-parser`. Can you maybe investigate this a bit more?
Also your versions seem fine, they are the latest and should work on normal circumstances.

**Comment by jwarykowski** [comment]
Hey @gabrielmfern, sorry on the delay here. Apologies, weird caching issue my side. Now working as expected although there now appears to be a media query problem with tailwind. I've mentioned this [here](https://github.com/resend/react-email/issues/1095#issuecomment-1865394227). Thanks again for all your help 🌟
