### ISSUE TITLE
Recreate Nike's order email

### ISSUE THREAD

**Issue by zenorocha** [resendlabs/react-email#113]
It's important that we try to recreate real emails in order to validate the quality and developer experience of our components. This is an example of an order confirmation email.

> Original: [Looking for Your Nike Order.eml.zip](https://github.com/zenorocha/react-email/files/9642524/Looking.for.Your.Nike.Order.eml.zip)

![CleanShot 2022-09-25 at 19 36 03@2x](https://user-images.githubusercontent.com/398893/192182893-43b73748-043c-462d-8c43-be00f5ab2534.png)

**Comment by camillegachido** [comment]
Hi Zeno! I would like to do this one, can you assign me?

**Comment by cassiorsfreitas** [comment]
Let's go! 💜

**Comment by zenorocha** [comment]
awesome!
