### ISSUE TITLE
Tailwind support in emails

### ISSUE THREAD

**Issue by john-griffin** [resendlabs/react-email#219]
It would be great if we could use Tailwind to style emails so we can use consistent tooling across web and email.

[Maizzle](https://maizzle.com) is a framework that support this but it's not react based.

Some way to take the CSS classes from Tailwind and inline those as styles would be required for this.

**Comment by arndvs** [comment]
If you're not aware, there is a package called mailwind: https://github.com/soheilpro/mailwind

It compiles Tailwind to CSS to design HTML emails. 

You may be able to draw inspiration or see how they're addressing tailwind to CSS  in emails.

It works, but there is a bit of rigamarole to it. 

It would be nice if react-email could do a similar process in the render function.

**Comment by DinoZoidDev** [comment]
This is what react email is missing! Please add this feature.

**Comment by Balance8** [comment]
Bump!

**Comment by zenorocha** [comment]
@vinicoder any updates on this?

**Comment by vinicoder** [comment]
Yeah @zenorocha! I created this PR recently with this feature. Check it out: https://github.com/resendlabs/react-email/pull/382

**Comment by Hahlh** [comment]
Awesome, thank you @vinicoder !
