### ISSUE TITLE
Add support for MDX

### ISSUE THREAD

**Issue by zenorocha** [resendlabs/react-email#27]
Inspiration:
* https://www.joshwcomeau.com/react/wonderful-emails-with-mjml-and-mdx/#composing-emails-with-mdx
* https://www.useplunk.com/markdown-to-email

Components needed:
* https://github.com/zenorocha/react-email/issues/53
* https://github.com/zenorocha/react-email/issues/52
* https://github.com/zenorocha/react-email/issues/49
* https://github.com/zenorocha/react-email/issues/48
* https://github.com/zenorocha/react-email/issues/42
* https://github.com/zenorocha/react-email/issues/13

**Comment by vcapretz** [comment]
Assigned myself for this one, going to work on it!
