### ISSUE TITLE
`dev` command does not work in yarn workspaces

### ISSUE THREAD

**Issue by IgnisDa** [resendlabs/react-email#292]
Using version `1.5.0`

I am using yarn workspaces. `react-email dev` fails with this error (the last step hangs indefinitely):

<img width="909" alt="image" src="https://user-images.githubusercontent.com/60938164/209424860-395477d5-aa0a-4893-81db-064d32148fbe.png">

Reproduction:

1. Clone https://github.com/IgnisDa/codefarem/tree/IgnisDa/issue23 (the `IgnisDa/issue23` branch) 
2. `cd apps/mails && npx react-email dev`

**Comment by IgnisDa** [comment]
Temporary workaround is to create a `yarn.lock` in it manually.

**Comment by aidankinzett** [comment]
this is working for me in a private repo, I just used the `yarn create email` command to make a new package

**Comment by juliencastera** [comment]
Does not work in an NX project too (nx is using npm, got package.lock, but react-email forces to use yarn. I also had to create a yarn.lock manually)

Hope for an update ! :)

**Comment by zenorocha** [comment]
@juliencastera we removed the hard requirement on Yarn, make sure you upgrade to the latest version.

**Comment by bukinoshita** [comment]
Closing this, feel free to re-open.
