### ISSUE TITLE
`export` command never terminates

### ISSUE THREAD

**Issue by IgnisDa** [resendlabs/react-email#293]
The `react-email build` command never terminates: 

<img width="664" alt="image" src="https://user-images.githubusercontent.com/60938164/209425518-3d361609-0397-4032-8012-6e361033cadf.png">

**Comment by bukinoshita** [comment]
Is this for the `build` or `export`?

**Comment by IgnisDa** [comment]
@bukinoshita It is for `export`.

**Comment by zenorocha** [comment]
@IgnisDa would you mind sharing what operating system you are using?

**Comment by IgnisDa** [comment]
I am using Arch Linux.

**Comment by IgnisDa** [comment]
Hello @zenorocha @bukinoshita any updates on this? You can reproduce it on this repo: https://github.com/IgnisDa/codefarem

Instructions:

```bash
cd apps/mails
npx react-email export
```

**Comment by bukinoshita** [comment]
Hi @IgnisDa I'm going to take a look this week alongside the https://github.com/resendlabs/react-email/issues/323

**Comment by bukinoshita** [comment]
@IgnisDa We just publish the v1.6.2, it fixes the issue. Let me know if you're still have any problem with export command.

**Comment by IgnisDa** [comment]
@bukinoshita It works now, thanks!
