### ISSUE TITLE
Support for  plain text renderer

### ISSUE THREAD

**Issue by goenning** [resendlabs/react-email#296]
Add ability to render a template into plain text, so we can send both html and text versions of the email. I guess some components (images, buttons) would not render anything during this operation.

**Comment by bukinoshita** [comment]
@goenning Is this to the `react-email` preview app?

**Comment by goenning** [comment]
not really. When I send emails with AWS SES for example, I always try to send both HTML and Text versions of it. So if the user prefers a text-only email, they'll see that version of the email, while those who prefer a richer experience will see the HTML version of it.

The suggestion here is to create a renderer that generates a plain-text string, without all the HTML tags, so that developers could generate a HTML and Plain Text email based off of a single react-email template.

I actually don't know if it's doable or if in-scope for the project at all, just throwing out some ideas here. 

End result would be something like this:

```js
import { renderAsHtml, renderAsPlainText } from '@react-email/render';

const emailHtml = renderAsHtml(<SomeTemplate url="https://example.com" />);
const emailText = renderAsPlainText(<SomeTemplate url="https://example.com" />);

const options = {
  Source: 'you@example.com',
  Destination: {
    ToAddresses: ['user@gmail.com'],
  },
  Message: {
    Body: {
      Html: {
        Charset: 'UTF-8',
        Data: emailHtml,
      },
      Text: {
        Charset: 'UTF-8',
        Data: emailText,
      },
    },
    Subject: {
      Charset: 'UTF-8',
      Data: 'hello world',
    },
  },
};
```

**Comment by bukinoshita** [comment]
Oh, okay. It's for the `render` package. Yeah, we should at least give it a try because this can be helpful. I like the idea

**Comment by zenorocha** [comment]
That's a great idea!

I remember seeing this online converter from Mailchimp:
https://templates.mailchimp.com/resources/html-to-text

Premailer also has something similar, where they return the text in UTF-8 format with all HTML tags removed:
https://premailer.github.io/premailer/HtmlToPlainText.html

Here's an idea for us: what if we used an HTML → Markdown converter to do this?

**Comment by alecharmon** [comment]
Heya! v interested in taking a shot at this if y'all need the extra hands

**Comment by alecharmon** [comment]
took a stab at it here https://github.com/zenorocha/react-email/pull/320
