### ISSUE TITLE
[Examples] Add a complex email template such as Paddle's transaction receipt

### ISSUE THREAD

**Issue by goenning** [resendlabs/react-email#297]
I think having this (or anything similarly complex) as a example would be great. Lots of tables, elements, alignment, positioning, etc.

![Screenshot 2022-12-26 at 11 37 53](https://user-images.githubusercontent.com/94755/209544846-b4e3944f-c05f-42b0-aaa0-cd8253cdcad0.png)

**Comment by EmersonGarrido** [comment]
A great example, would you be able to send me this model in my email?

I have a few hours available to create the models.

I would like to create this model.
My email is pinned to my github profile.

**Comment by goenning** [comment]
@EmersonGarrido  Done, sent you an email

**Comment by zenorocha** [comment]
We got two new templates that fix this exact same use case with pretty complex columns and rows:
* https://demo.react.email/preview/apple-receipt
* https://demo.react.email/preview/nike-receipt
