### ISSUE TITLE
Replace <td> tags with <Column /> component

### ISSUE THREAD

**Issue by zenorocha** [resendlabs/react-email#307]
1. https://github.com/zenorocha/react-email/blob/main/apps/demo/emails/google-play-policy-update.tsx#L99-L129
2. https://github.com/zenorocha/react-email/blob/main/apps/demo/emails/slack-confirm.tsx#L41-L86
3. https://github.com/zenorocha/react-email/blob/main/apps/demo/emails/vercel-invite-user.tsx#L43-L76

**Comment by cassiorsfreitas** [comment]
Section and Column version 0.0.3 https://github.com/zenorocha/react-email/pull/308 in review
