### ISSUE TITLE
`<Column />` component inside a `<Section />` render extra td elements

### ISSUE THREAD

**Issue by matuzalemsteles** [resendlabs/react-email#309]
If you have to composite the `Column` component with the `Section` you have an unexpected output from rendering nested `<td />`. This will behave differently when using `render` instead of nested being children of `<Column />` but in the end they all have the same source of the problem. See this output example in codesandbox https://codesandbox.io/s/blazing-cache-mlremw?file=/src/App.js.

```jsx
<Section>
  <Column>Column</Column>
  <Column>Column</Column>
</Section>
```

Output:

```jsx
// Runtime
<tr>
  <td>
    <td>Column</td>
  </td>
  <td>
    <td>Column</td>
  </td>
</tr>

// Server
<tr>
  <td></td>
  <td>Column</td>
  <td></td>
  <td>Column</td>
</tr>
```

The problem is more on the server because it renders extra elements which creates extra columns breaking the layout, probably the error must be in the component check of `<Section />` that when validating if the child is a `td` element https://github.com/zenorocha/react-email/blob/d2bcbd3e60cd30e3a68752c8aeb0cb2d06e44fef/packages/section/src/section.tsx#L26, as `Column` is a component this breaks the conditional, a solution to this would be to maybe check the component name, something like:

```js
return React.isValidElement(child) && (child.type === "td" || child.type.displayName === 'Column');
```

**Comment by cassiorsfreitas** [comment]
Hey @matuzalemsteles thanks for reporting. What are the Column and Section versions?

**Comment by matuzalemsteles** [comment]
Hi @cassiorsfreitas, I'm using these versions:

- `Column` v0.0.3
- `Section` v0.0.4

Yeah I see, that's why the idea is to get the name of the components through `type.displayName` it doesn't change when it happens in the build phase just the name of the function, `displayName` stores a string in a object and the minification should not affect this, object values cannot be changed.

**Comment by cassiorsfreitas** [comment]
@matuzalemsteles What do you think? https://github.com/zenorocha/react-email/pull/312

**Comment by matuzalemsteles** [comment]
Cool, looks great. Thanks!
