### ISSUE TITLE
"Local Development" image in docs is broken

### ISSUE THREAD

**Issue by MatthewStanciu** [resendlabs/react-email#359]
I saw this on both https://react.email/docs/getting-started/automatic-setup and https://react.email/docs/getting-started/manual-setup.

<img width="820" alt="Screenshot 2023-01-18 at 10 51 03 PM" src="https://user-images.githubusercontent.com/14811170/213351335-c99fc85f-4ec7-4532-9573-866a77611610.png">

<img width="687" alt="Screenshot 2023-01-18 at 10 51 08 PM" src="https://user-images.githubusercontent.com/14811170/213351343-6f4f46aa-0e09-40f1-8459-839ed6e9d504.png">

<img width="766" alt="Screenshot 2023-01-18 at 10 53 18 PM" src="https://user-images.githubusercontent.com/14811170/213351382-6bb785bd-64a4-40f2-9725-b6eded9afc00.png">

**Comment by bukinoshita** [comment]
This was fixed on https://github.com/resendlabs/react-email/pull/358
