### ISSUE TITLE
Add <Heading /> Component

### ISSUE THREAD

**Issue by Sayantan-s** [resendlabs/react-email#362]
I think having a `<Heading />` component alongside the `<Text />` component would actually be a great DX.

**Comment by bukinoshita** [comment]
We do have it [here](https://github.com/resendlabs/react-email/tree/main/packages/heading), I think we missed in the readme though

**Comment by Sayantan-s** [comment]
That's cool, but it's not included in the component documentation.

**Comment by bukinoshita** [comment]
Fixed by https://github.com/resendlabs/react-email/pull/370

**Comment by zenorocha** [comment]
Here's the full documentation: https://react.email/docs/components/heading

Thanks for pointing it out @Sayantan-s!
