### ISSUE TITLE
Support for props in the preview app 

### ISSUE THREAD

**Issue by guillaumelachaud** [resendlabs/react-email#371]
Hi!

It would be great if the preview app could be used to edit props of a specific email. That could be useful to test out edge cases with long values, different alphabets,...

Would also be nice if we could supply default values only meant to be used for the preview app.

**Comment by ImBaedin** [comment]
I support this suggestion, however there is a solid solution for the default value problem.

You can destructure your prop object and add whatever defaults you want.

When the preview app renders the email, the defaults are used:

```email.tsx
interface EmailProps {
  /**
   * User's first name
   */
  firstname: string;
  /**
   * User's last name
   */
  lastname: string;
}

const Email: React.FC<EmailProps> = ({
  firstname = "John",
  lastname = "Doe",
}) => {
  return (
    <Html>
      <Section>
        <Text>
          Hello {firstname} {lastname}
        </Text>
      </Section>
    </Html>
  );
};
```
![image](https://user-images.githubusercontent.com/7637729/214214154-1e1c6370-469a-4f48-b862-91bb22092922.png)

Best part of this solution is that even though you supply defaults and the preview app doesn't throw an error, the typescript server does:
![image](https://user-images.githubusercontent.com/7637729/214214366-2acb1281-8dbb-415f-a463-a325bcb65941.png)

**Comment by zenorocha** [comment]
This is a SUPER interesting feature.

An inspiration that came to mind was Microlink Cards: https://cards.microlink.io/editor?preset=workos

<img width="1508" alt="CleanShot 2023-01-23 at 22 43 03@2x" src="https://user-images.githubusercontent.com/398893/214228130-af911683-481b-42d1-86bf-36d2bf312070.png">

**Comment by zenorocha** [comment]
Great point about the default values @ImBaedin, I feel like we should update all demos to contain that pattern. Do you want to send a PR?

**Comment by ImBaedin** [comment]
> Great point about the default values @ImBaedin, I feel like we should update all demos to contain that pattern. Do you want to send a PR?

You're talking about [these demos](https://github.com/resendlabs/react-email/tree/main/apps/demo/emails) right?
If so, sounds like fun 😊

**Comment by zenorocha** [comment]
Yep ;)

**Comment by ImBaedin** [comment]
> Yep ;)

#377
