### ISSUE TITLE
Add option change the port that the dev server runs on

### ISSUE THREAD

**Issue by zenorocha** [resendlabs/react-email#372]
Desired behavior:

```json
"scripts": {
    "dev": "email dev -p 3001",
}
```

**Comment by zenorocha** [comment]
it's live now @sneakyvv, @gra0007, @caseypugh, get v1.7.9 to get it

**Comment by gokulkrishh** [comment]
@zenorocha I was searching for this ended up finding in closed issues, is it possible to enable discussions in this repo? It would be lot easier to ask/create discussions related to react-email. Like [supabase](https://github.com/supabase/supabase/discussions) is doing.
