### ISSUE TITLE
Issue on docs: How to set Img src from nextjs 

### ISSUE THREAD

**Issue by b0iq** [resendlabs/react-email#380]
Path: /components/image.mdx

The issue is I tried to include local image to my image which is logo and its located under `./public/logo/logo_full.jpg`
so I tried these and none of them works:
1. ```<Img src={`${baseUrl}/static/logo/logo_full.jpg`} />```
2. ```<Img src={`${baseUrl}/logo/logo_full.jpg`} />```
3. ```<Img src='/logo/logo_full.jpg' />```

I think the docs missing that how to use image path. or react-email way of copying images...

framework: nextjs 13
package manager: yarn
js engine: node 18.2.0

**Comment by bukinoshita** [comment]
We have this setup in our demo app, does this help you? Let me know if you still have any issue.

https://github.com/resendlabs/react-email/blob/main/apps/demo/emails/airbnb-review.tsx#L14

**Comment by b0iq** [comment]
Sorry the late response. 

The static folder I don’t think it in nextjs they have public folder and when I build the project it not moving the images to the static

**Comment by teofanis** [comment]
@b0iq If you have an image in your public folder of your next js app, next js will serve it by accessing the url : your-app.url/image-file-in-public-folder.jpg.

Check this for more information on Next JS Static file serving : https://nextjs.org/docs/basic-features/static-file-serving
Another way you can try is by importing the local file and using it in the src - see more here : https://nextjs.org/docs/basic-features/image-optimization#local-images
