### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by caseypugh** [resendlabs/react-email#389]
I'm just getting started and followed the [automatic setup guide](https://react.email/docs/getting-started/automatic-setup) and hot reloading doesnt work out of the box. I have to manually refresh the browser. Sometimes manually refreshing doesnt even work and I have to restart the server.

I also tested manually editing the generated emails within `.react-email/emails/*.tsx` and it seemed to do nothing.

### Steps to recreate
```bash
npx create-email@latest
cd react-email-starter
npm install
npm run dev
```

open `localhost:3000` and edit one of the email templates. 

### System info
Tested on multiple computers and node versions.
- Node `18.13.0`, `18.11.0`, and `16.17.0`
- Windows & MacOS 12.5.1 M1
- Firefox & Chrome

<details>
  <summary><h3>package.json</h3></summary>
This is what is generated from `npx create-email@latest` 

```json
{
  "name": "emails",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "email dev",
    "export": "email export"
  },
  "dependencies": {
    "@react-email/button": "^0.0.4",
    "@react-email/container": "^0.0.4",
    "@react-email/head": "^0.0.2",
    "@react-email/heading": "^0.0.5",
    "@react-email/hr": "^0.0.2",
    "@react-email/html": "^0.0.2",
    "@react-email/img": "^0.0.2",
    "@react-email/link": "^0.0.2",
    "@react-email/preview": "^0.0.2",
    "@react-email/section": "^0.0.1",
    "@react-email/text": "^0.0.2",
    "react-email": "^1.5.0"
  }
}
```
</details>

**Comment by caseypugh** [comment]
This might be an issue with next `13.0.4`? Possibly connected https://github.com/vercel/next.js/issues/43396

**Comment by bukinoshita** [comment]
Closing this in favor of https://github.com/resendlabs/react-email/issues/92.
