### ISSUE TITLE
Fix Apple email template

### ISSUE THREAD

**Issue by zenorocha** [resendlabs/react-email#402]
Current result:

<img width="629" alt="CleanShot 2023-01-27 at 20 39 33@2x" src="https://user-images.githubusercontent.com/398893/215242329-21b7b0f2-5d0e-4ab6-85c7-b26e23227df3.png">

Desired result:

<img width="686" alt="CleanShot 2023-01-27 at 20 37 59@2x" src="https://user-images.githubusercontent.com/398893/215242287-1872923d-989a-4b48-939f-5566503d0e99.png">

**Comment by zenorocha** [comment]
@relferreira can you take a look? https://demo.react.email/preview/apple-receipt

**Comment by relferreira** [comment]
@zenorocha I've made a PR that hopefully fixes this 

https://github.com/resendlabs/react-email/pull/406

Sorry for the inconvenience

**Comment by zenorocha** [comment]
@relferreira no worries, thanks for the quick fix!
