### ISSUE TITLE
Column component

### ISSUE THREAD

**Issue by ffiona** [resendlabs/react-email#432]
I remember there was an issue with an extra `td` being added in a table. It was fixed, however new version of component has visual issues in Gmail web client. Columns 0.0.3 version didn't have styles for `tr` tag, new one has `display: grid` and looks like it's not fully supported. Everything is ok in Apple mail btw.

I had to downgrade all components in order to prevent my current templates being broken, but I'd like to keep them updated in future and to be sure the compatibility stays the same.

This is how my template looked like in Gmail web before version bump:

<img width="1356" alt="0 0 3" src="https://user-images.githubusercontent.com/1404938/216315883-440661d3-aa73-4ff8-9732-5b2b564878fa.png">

And how it looks now:

<img width="1356" alt="0 0 5" src="https://user-images.githubusercontent.com/1404938/216316011-30dbc2f0-9901-4afe-99a7-b4537f27fa96.png">

**Comment by bukinoshita** [comment]
We have a canary version for the column and doing some testing with it.

**Comment by ffiona** [comment]
@bukinoshita thank you for the reply 👍

**Comment by bukinoshita** [comment]
@ffiona I just release a new version for `@react-email/column`.

For the structure, try to use the following

`Html -> Body -> Container -> Section -> Row -> Column`

In this PR you can get an idea: https://github.com/resendlabs/react-email/pull/457.

Let me know if you still have any issue with the component and we can re-open this issue.
