### ISSUE TITLE
[Dev] local sertup Cannot find module '@react-email/render'

### ISSUE THREAD

**Issue by leonardobrito** [resendlabs/react-email#434]
Hi guys, I'm trying to setup locally the project and I'm not figuring out whats going wrong:

First I've tried  install the dependencies using `yarn`, the process stops here and don't finish:
<img width="750" alt="Screenshot 2023-02-02 at 11 49 02" src="https://user-images.githubusercontent.com/2532291/216383218-c4f31541-f69f-4725-8bce-6daefe396d4c.png">

After that I try to install with `npm` and receive this error:
```shell
npm ERR! code 1
npm ERR! path /Users/{computer-user}/dev/react-email/packages/react-email
npm ERR! command failed
npm ERR! command sh -c npm run build
npm ERR! > react-email@1.7.10 build
npm ERR! > tsc
npm ERR! 
npm ERR! source/commands/export.ts:6:33 - error TS2307: Cannot find module '@react-email/render' or its corresponding type declarations.
npm ERR! 
npm ERR! 6 import { render, Options } from '@react-email/render';
npm ERR!                                   ~~~~~~~~~~~~~~~~~~~~~
npm ERR! 
npm ERR! 
npm ERR! Found 1 error in source/commands/export.ts:6
npm ERR! npm ERR! Lifecycle script `build` failed with error: 
npm ERR! npm ERR! Error: command failed 
npm ERR! npm ERR!   in workspace: react-email@1.7.10 
npm ERR! npm ERR!   at location: /Users/{computer-user}/dev/react-email/packages/react-email

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/{computer-user}/.npm/_logs/2023-02-02T15_02_05_206Z-debug-0.log
```

Anyone with the same problem? Did I miss some setting?

**Comment by ElanUtta** [comment]
@leonardobrito The first case occurs with me too. It freeze my M1, and I needed to restart it. To solve it, I just send the `npx run dev `, and worked.

**Comment by leonardobrito** [comment]
> @leonardobrito The first case occurs with me too. It freeze my M1, and I needed to restart it. To solve it, I just send the `npm run dev `, and worked.

Thanks @ElanUtta, I tried again now install with `yarn` from the scratch and everything is working now.
I believe some dependence were not being resolved yesterday. 

The project is up now. 🙏🏻

My M1 was freeze too. 😄
