### ISSUE TITLE
--dir option causes crash when modifying files

### ISSUE THREAD

**Issue by tefkah** [resendlabs/react-email#436]
For me at least, `react-email` does not seem like having the root `package.json` be in a different folder than the email templates.

When I run `pnpm exec email dev --dir apps/email/dir` (or `yarn` equiv), when making changes the server crashes with
```sh
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
NestedError: Cannot copy `ROOT/apps/email/emails/email/emails/stripe-welcome.tsx`: the file doesn't exist
    at ROOT/node_modules/.pnpm/cpy@8.1.2/node_modules/cpy/index.js:96:10
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FSWatcher.<anonymous> (ROOT/node_modules/.pnpm/react-email@1.7.10/node_modules/react-email/dist/source/utils/watcher.js:37:9) {
  nested: undefined,
  name: 'CpyError'
}
```

It seems to "double" look for the emails, adding `email/emails` after that has already been added.

CodeSandbox that reproduces this issue (with Yarn, without NX): https://codesandbox.io/p/sandbox/sleepy-water-1vh8oi?file=%2Fapps%2Femail%2Femails%2Fnotion-magic-link.tsx&selection=%5B%7B%22endColumn%22%3A52%2C%22endLineNumber%22%3A1%2C%22startColumn%22%3A52%2C%22startLineNumber%22%3A1%7D%5D

**Comment by cmnord** [comment]
https://github.com/resendlabs/react-email/pull/445 fixes this if you want to pull in the patch yourself

**Comment by bukinoshita** [comment]
We also pushed https://github.com/resendlabs/react-email/pull/460, let me know if you still have any issues with it.

**Comment by tefkah** [comment]
Exact same issue still occurs, see https://codesandbox.io/p/sandbox/naughty-hamilton-905g9d?file=%2F.codesandbox%2Ftasks.json&selection=%5B%7B%22endColumn%22%3A25%2C%22endLineNumber%22%3A24%2C%22startColumn%22%3A25%2C%22startLineNumber%22%3A24%7D%5D

**Comment by shiyuanhai** [comment]
@bukinoshita hey would you please release on NPM thus we can use it?
