### ISSUE TITLE
Command for Automatic Deployment does not work!

### ISSUE THREAD

**Issue by AnimeshRy** [resendlabs/react-email#437]
[](url)As the title says, the command in the docs for creating the starter template does not work for me. Is there any specific npm or node version needed for this ? If yes then we should add that to the docs as well.
<img width="627" alt="Screenshot 2023-02-03 103900" src="https://user-images.githubusercontent.com/54435702/216517537-6d70bd0b-3bb1-4608-9bdb-cdea04077743.png">

**Comment by ElanUtta** [comment]
@AnimeshRy I just tried this `npx creat-email@latest` command, and everything was OK. Can you specify your node version and other things you fill it is important?

**Comment by bukinoshita** [comment]
@AnimeshRy Can you share your node version?

**Comment by AnimeshRy** [comment]
16.13.2
nvm -> 0.39.0

<img width="581" alt="Screenshot 2023-02-07 191145" src="https://user-images.githubusercontent.com/54435702/217261275-a5bd02d6-5a40-42ac-806e-018562fe2ec6.png">

**Comment by Forsto2012** [comment]
I also ran into the same issue. After updating to v18.12.0 it worked fine.

**Comment by AnimeshRy** [comment]
Yeah, It works on other version fine. We still need to find the cause of the problem

**Comment by bukinoshita** [comment]
@AnimeshRy Can you try the latest version with node >16?

**Comment by AnimeshRy** [comment]
@bukinoshita As I said, it works fine on other versions. The issue is about not working with this specific version. It's cool if you wanna close it but I feel the issue still exists or maybe lets add this in the docs to use node >16

**Comment by bukinoshita** [comment]
Oh okay, we do have the node version [here](https://github.com/resendlabs/react-email/blob/main/packages/create-email/package.json#L24-L26). It you're using an older version, it should throw a warning in your terminal.

**Comment by AnimeshRy** [comment]
Ok cool!
