### ISSUE TITLE
[DEV] Connection was refused by the server.

### ISSUE THREAD

**Issue by vorvex** [resendlabs/react-email#439]
when running npm run dev I get a connection was refused eventhough the terminal says ready.
 
✔ Dependencies installed

> react-email-preview@0.0.11 dev
> next dev "-p" "3000"

ready - started server on 0.0.0.0:3000, url: http://localhost:3000

I noticed that the server was started on 0.0.0.0:3000 which I have never seen before.

**Comment by vorvex** [comment]
Looked deeper into this and seems like that next dev has the following Error
```Segmentation fault: 11```

**Comment by bukinoshita** [comment]
Closing this, let me know if you still have any issue.
