### ISSUE TITLE
Add MailerSend as an email provider

### ISSUE THREAD

**Issue by Agathe-Brusset** [resendlabs/react-email#444]
Hello to the React Email team,
I'm Agathe Brusset, product manager of [MailerSend](https://www.mailersend.com), a solution to send transactional emails via API or SMTP. We would love to connect MailerSend to React Email and be featured as an additional Email provider. Would you consider adding an example to send an email with MailerSend on your documentation?

Here is our [Node.js SDK](https://github.com/mailersend/mailersend-nodejs)

Thank you,
Agathe.

**Comment by bukinoshita** [comment]
> Hello to the React Email team, I'm Agathe Brusset, product manager of [MailerSend](https://www.mailersend.com), a solution to send transactional emails via API or SMTP. We would love to connect MailerSend to React Email and be featured as an additional Email provider. Would you consider adding an example to send an email with MailerSend on your documentation?
> 
> Here is our [Node.js SDK](https://github.com/mailersend/mailersend-nodejs)
> 
> Thank you, Agathe.

That would be great! Is anyone from MailerSend interest in contributing to add this example?
