### ISSUE TITLE
Setting Up Project 

### ISSUE THREAD

**Issue by uhrohraggy** [resendlabs/react-email#450]
In trying to follow the manual setup instructions, we ended up with an error trying to run the dev server that appears to to relate to workspace issues and/or not loading full dependencies properly. I'm using a React Remix app and not Next.JS.  Our package.json includes 

```
"scripts": [
  "dev:email": "email dev --dir app/mailers --port 3001",
  ...
],
...
"workspaces": [
    ".react-email",
```

from an earlier error message:
```
Usage Error: The nearest package directory (/project-dir/.react-email) doesn't seem to be part of the project declared in /project-dir.

- If /project-dir/ isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /project-dir/ is intended to be a project, it might be that you forgot to list .react-email in its workspace configuration.
- Finally, if /project-dir is fine and you intend .react-email to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.
```

After adding that and re-running `yarn`, we're getting an error when running yarn dev:

```
error - Font loader error:
Cannot find module 'next/dist/server/font-utils'
Require stack:
- /project-dir/node_modules/@next/font/dist/google/loader.js
- /project-dir/node_modules/@next/font/google/loader.js
- /project-dir/.react-email/node_modules/next/dist/build/webpack/loaders/next-font-loader/index.js
- /project-dir/.react-email/node_modules/next/dist/compiled/webpack/bundle5.js
- /project-dir/.react-email/node_modules/next/dist/compiled/webpack/webpack.js
- /project-dir/.react-email/node_modules/next/dist/server/config-utils.js
- /project-dir/.react-email/node_modules/next/dist/server/config.js
- /project-dir/.react-email/node_modules/next/dist/server/next.js
- /project-dir/.react-email/node_modules/next/dist/server/lib/start-server.js
- /project-dir/.react-email/node_modules/next/dist/cli/next-dev.js
- /project-dir/.react-email/node_modules/next/dist/lib/commands.js
- /project-dir/.react-email/node_modules/next/dist/bin/next
```

I'm using yarn version berry (3.3.1) in case that makes a difference.

**Comment by bastiaanv** [comment]
I got it running without any problems. I did the following:
- Run `npx create-remix@latest` with:
  - Name: `remix`
  - Type: `Pre-configured`
  - Stack: `Indie`
  - Ts or JS: `Ts`
  - Run npm install: `Yes`
- After the installation, I created a folder `app/mailers` and created a file named: `test.tsx` with [this as its content](https://react.email/docs/getting-started/manual-setup#4-include-email-template)
- Installed some basic `react-email` packages with: `npm install react-email @react-email/button @react-email/html -E`
- Added the dev command via (Note: I did not add workspaces or anything else):
```json
{
  "scripts": {
    "dev:email": "email dev --dir app/mailers"
}
```
- Now everything is setup and I could run `npm run dev:email` with the following output:
```
➜ npm run dev:email

> dev:email
> email dev --dir app/mailers

✔ Emails preview generated
⠋ Installing dependencies...

up to date, audited 572 packages in 1s

68 packages are looking for funding
  run `npm fund` for details

5 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

✔ Dependencies installed

> react-email-preview@0.0.11 dev
> next dev -p 3000

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 1625 ms (190 modules)
wait  - compiling...
event - compiled successfully in 121 ms (158 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 467 ms (658 modules)
```

Note: Everything also worked with `yarn`. I have version: `v1.22.19`

Can you try this? And if this still does not work, can you share your file structure and other maybe useful information about your repository/project?

**Comment by bukinoshita** [comment]
Closing this @uhrohraggy, let me know if you still have the issue
