### ISSUE TITLE
tailwind background img is not rendering correctly

### ISSUE THREAD

**Issue by TobiasLueger** [resendlabs/react-email#451]
Hey,

today I stumbled upon a Tailwind-Component problem. 
When i use the bg-[url...] then it breaks my styles:

`
<Column className="bg-[url('https://i.ibb.co/VMYpcKz/Tag-Rabatt.png')] block text-[10px] leading-[15px] text-white min-w-[69px] bg-no-repeat ">
    <Text className="text-[10px] leading-[15px] text-white">-{rabatt}% Rabatt *</Text>
</Column>
`

in rendered styles:

![Bildschirm­foto 2023-02-08 um 10 32 18](https://user-images.githubusercontent.com/44581179/217490579-27d4d4ae-80a3-41d0-808d-f1c581209acc.png)

I am using "react-email": "1.7.10", "tailwindcss": "^3.2.4",

Thanks for the awesome react email package <3

**Comment by heysujal** [comment]
It might be due to this bug which I am fixing 
https://github.com/resendlabs/react-email/issues/442

**Comment by bukinoshita** [comment]
Yup, going to close this in favor of #442
