### ISSUE TITLE
Render email in API route

### ISSUE THREAD

**Issue by ernestasga** [resendlabs/react-email#461]
I have just recently discovered this project and it is amazing! I have build some emails and now I need to render and send them with Nodemailer inside an API route. The problem is that api routes have .ts extension, so it's not possible to get react components inside. My quick fix was to use .tsx extension in api route. I was wondering if there is a different way to render the email inside .ts file, or is it just fine to use .tsx?

**Comment by bastiaanv** [comment]
Hi @ernestasga,

For a `.ts` (NodeJS) solution, you can take a look [here](https://react.email/docs/integrations/overview) and [here (inside the NodeJS-tab)](https://react.email/docs/integrations/nodemailer#3-convert-to-html-and-send-email).

If the documentation isn't clear, please let me know!

**Comment by ernestasga** [comment]
That's exactly what I was looking for, thanks!
