### ISSUE TITLE
Responsive column

### ISSUE THREAD

**Issue by DenisLaboureyras** [resendlabs/react-email#462]
Thanks for your awesome library !

I'm using MJML to create my e-mails template, and the feature I'm missing to migrate to React E-mail is their responsive column.
With MJML, you can specify the column width in percent (50%, 70%, ...) and in responsive, columns are displayed 1 by row.
I would be thrilled to see this feature in React Email as well.

Do you think it is something that can be added to the library roadmap ?

If not, I think it is something that I can achieve with your Tailwind plugin (after the new version taking into account media queries).

Here is an example of generated html by MJML:
```
<style type="text/css">
    @media only screen and (min-width:480px) {
      .mj-column-per-100 {
        width: 100% !important;
        max-width: 100%;
      }

      .mj-column-per-30 {
        width: 30% !important;
        max-width: 30%;
      }

      .mj-column-per-70 {
        width: 70% !important;
        max-width: 70%;
      }
    }

  </style>
  <style media="screen and (min-width:480px)">
    .moz-text-html .mj-column-per-100 {
      width: 100% !important;
      max-width: 100%;
    }

    .moz-text-html .mj-column-per-30 {
      width: 30% !important;
      max-width: 30%;
    }

    .moz-text-html .mj-column-per-70 {
      width: 70% !important;
      max-width: 70%;
    }

  </style>


<!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td class="" style="vertical-align:top;width:171px;" ><![endif]-->
                        <div class="mj-column-per-30 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;">
...
</div>
```

**Comment by MrVladevoit** [comment]
+

**Comment by MrVladevoit** [comment]
`Test Message with [link](https://github.com/resendlabs/react-email/issues/462)`

**Comment by rigoarpi** [comment]
Hi! Is this already doable? Can you please share a snippet about how to achieve this? I'd like to do the exact same thing, but yet to find a great solution.

**Comment by JanKups** [comment]
@vinicoder How would we adjust the <Row> or <Column> to have different amount on mobile vs desktop with tailwind?

**Comment by bukinoshita** [comment]
@rigoarpi  @JanKups Would mind sharing a screenshot or something that you're trying to achieve?

**Comment by vinicoder** [comment]
Hey guys! @JanKups @rigoarpi @bukinoshita 

Here's a simple example of how to create responsive columns:

```tsx
import {
  Container,
  Html,
  Section,
  Tailwind,
  Head,
} from "@react-email/components";

export default function Email() {
  return (
    <Tailwind>
      <Html>
        <Head />
        <body>
          <Section className="bg-white my-auto mx-auto font-sans">
            <Container className="border border-solid border-[#eaeaea] rounded my-[40px] mx-auto p-[20px] w-[465px]">
              <div className="text-[0]">
                <div className="inline-block w-full lg:w-1/3 bg-red-500 h-96 text-lg text-white">
                  <div className="p-4">Column 1</div>
                </div>
                <div className="inline-block w-full md:w-1/2 lg:w-1/3 bg-blue-500 h-96 text-lg text-white">
                  <div className="p-4">Column 2</div>
                </div>
                <div className="inline-block w-full md:w-1/2 lg:w-1/3 bg-yellow-500 h-96 text-lg text-white">
                  <div className="p-4">Column 3</div>
                </div>
              </div>
            </Container>
          </Section>
        </body>
      </Html>
    </Tailwind>
  );
}

```

https://user-images.githubusercontent.com/3522573/230608234-a7977bf6-b0ed-41f7-93fc-ebcc775166fe.mp4

**Comment by JanKups** [comment]
@vinicoder Great example thanks!

An issue comes up when using this structure: It looks like styles are overwritten when <Tailwind> is used in combination with responsive styles.

Example where the link has the wrong color:

```
import * as React from "react";
import {
  Container,
  Html,
  Section,
  Tailwind,
  Head,
  Link,
} from "@react-email/components";

export default function Email() {
  return (
    <Tailwind>
      <Html>
        <Head />
        <body>
          <Section className="bg-white my-auto mx-auto font-sans">
            <Container className="border border-solid border-[#eaeaea] rounded my-[40px] mx-auto p-[20px] w-[465px]">
              <div className="text-[0]">
                <div className="inline-block w-full lg:w-1/3 bg-red-500 h-96 text-lg text-white">
                  <div className="p-4">Column 1</div>
                </div>
                <div className="inline-block w-full md:w-1/2 lg:w-1/3 bg-gray-50 h-96 text-lg text-white">
                  <Link className="p-4 text-green-400">Green Link</Link>
                </div>
                <div className="inline-block w-full md:w-1/2 lg:w-1/3 bg-yellow-500 h-96 text-lg text-white">
                  <div className="p-4">Column 3</div>
                </div>
              </div>
            </Container>
          </Section>
        </body>
      </Html>
    </Tailwind>
  );
}
```

Related issue: https://github.com/resendlabs/react-email/issues/517#issuecomment-1453880536

**Comment by vinicoder** [comment]
@JanKups Thanks, man! I'm currently working on better documentation for that component. Here's the explanation for this issue: https://github.com/resendlabs/react-email/pull/508#issuecomment-1501346832

**Comment by riad40** [comment]
@JanKups somehow this doesn't work on gmail

**Comment by BarakChamo** [comment]
@JanKups can you explain how come this works in your example:

```jsx
<Tailwind>
   <Html>
      <Head />
  </Html>
</Tailwind>

```

When I try a similar structure, I get:
```
Error: Tailwind: To use responsive styles you must have a <head> element as a direct child of the Tailwind component.
```

But when the `<Tailwind>` component is nested inside the HTML, and the error goes away, Gmail flattens all classes and non of the media queries work.

**Comment by gabrielmfern** [comment]
@BarakChamo As the error mentions, you must have a `<head>` directly below the `Tailwind` component. We made this change, I believe, on the new 0.0.13 release. This worked before because we would check for an `<html>` and then a `<head>`, but now we check directly for the `<head>`.
So, if you want the error to go away, try changing your structure to something like:

```jsx
<Html>
  <Tailwind>
    <Head />
  </Tailwind>
</Html>
```

**Comment by BarakChamo** [comment]
@gabrielmfern running `latest` I was getting the error I mentioned, but when applying your solution responsive styles were flattened by Gmail.

running `canary` I was able to move `<Tailwind/>` back to top level and responsive styles are working on Gmail.

not sure if this is intended behavior according to your reply, but that’s the only version + structure that yielded working media queries and no errors.

**Comment by gabrielmfern** [comment]
@BarakChamo 

> but when applying your solution responsive styles were flattened by Gmail.

This might be because of a lot of reasons, but what first comes to mind is because media queries had escaped characters, which on Gmail, end up being stripped away. So this isn't something particular to the solution I mentioned. As I said, this is the expected structure for the current versions of Tailwind.

> running canary I was able to move <Tailwind/> back to top level and responsive styles are working on Gmail.

The part of the styles working on Gmail might be because we fixed the escaped characters on selectors. The one for moving the `<Tailwind>` back up was because we changed it to detect the `<head>` element at any depth, which fixed a few issues, so you can also use that structure on the canary version.
See [release notes for @react-email/tailwind@0.0.15-canary.1](https://github.com/resend/react-email/releases/tag/%40react-email%2Ftailwind%400.0.15-canary.1)

**Comment by BarakChamo** [comment]
@gabrielmfern thanks for clarifying
