### ISSUE TITLE
Question: Plain text expected behaviour

### ISSUE THREAD

**Issue by magicspon** [resendlabs/react-email#474]
Hello,

https://react.email/docs/utilities/render#4-convert-to-plain-text

With this option enabled, is the expected result plain text for everyone? 

I'm using this with postmark.  I was expecting the plaint text version to be used when the client receiving the email doesn't allow html.  Is this the expected behaviour?

thanks

**Comment by bukinoshita** [comment]
In Postmark, are you passing the text in the `TextBody`?

eg:

```tsx
const text = render(<MyTemplate />, {
  plainText: true,
});


client.sendEmail({
  "From": "sender@example.com",
  "To": "recipient@example.com",
  "Subject": "Test",
  "TextBody": text
});
```

**Comment by magicspon** [comment]
that'll be the issue then.  I wasn't aware of the TextBody property.

thanks for the mega quick response.
