### ISSUE TITLE
Please help clarify install requirements

### ISSUE THREAD

**Issue by grmatthews** [resendlabs/react-email#485]
To install react-email, should I just be able to do `npm install react-email @react-email/html` and so on in my project, and then just proceed to incorporate the react-email components into my .jsx pages?

I have posted an issue on this before but it never got resolved.
- When I created a sandbox it all works fine, i.e. email renders ok in sandbox, however
- When I import the react email components into my project and try to render a very simple email (same as in sandbox) I get the following error:

```
./node_modules/@react-email/render/dist/index.mjs
Attempted import error: 'convert' is not exported from 'html-to-text'.
```

**Can anyone suggest how I could troubleshoot this?**

Obviously creating another sandbox is a waste of time, because that works ok, so nothing can be learnt from that.

The issue has something to do with my environment
- node -v => v18.13.0
- npm -v => 8.19.3

- react-dom@18.2.0
- @react-email/head@0.0.4
- @react-email/html@0.0.4
- @react-email/preview@0.0.5
- @react-email/render@0.0.6
- react-email@1.7.13

**Comment by bukinoshita** [comment]
> When I import the react email components into my project and try to render a very simple email 

Can you share that component you created?

**Comment by grmatthews** [comment]
```
// npm install react-email @react-email/html @react-email/preview @react-email/head @react-email/render

import { Head } from "@react-email/head"
import { Html } from "@react-email/html"
import { Preview } from "@react-email/preview"

const OTPMessage = (props) => {
    return (
        <Html>
            <Head />
            <Preview>Log in with this 6-digit code</Preview>
        </Html>
    )
}

export default OTPMessage
```

**Comment by bukinoshita** [comment]
It looks like you're trying to send OTP message emails using react-email, right? What are you using to send emails and what are you using in the backend?

I'm asking this because this `then just proceed to incorporate the react-email components into my .jsx pages` seems odd. You may want to import react-email to the sending email library you're using instead of a page.

**Comment by grmatthews** [comment]
I use SendGrid on the backend and can send out emails ok.

The fact I've chosen to use an OTP message to test react-email is a bit irrelevant - as you can see in the above React code, there's no generation of the OTP number, and it's a static 'hello world' type example.

Initially, I planned to develop the email template in react template on the client side so I can play around with react-email and learn how to use it, then use a call to render() to get the actual HTML message text, and then pass this to the back end to send through SendGrid.

Once the template was stable, I guessed I'd be able to do the HTML message text rendering server-side.

So, I am seeking help on why it's not working in my environment, not what a final application architecture might be - not relevant here.

**Comment by bukinoshita** [comment]
It's hard to debug or know what's happening in your code because I don't have access to your backend code or client-side. I'd recommend taking a look at [Sendgrid integration](https://github.com/resendlabs/react-email/blob/main/examples/sendgrid/src/index.tsx). And try to make the minimal work at first and try to isolate the part or issue you're having.

**Comment by grmatthews** [comment]
It has nothing to do with SendGrid at this stage.

I am simply trying to render some text using the react-email render method.

**Comment by zenorocha** [comment]
Have you checked some of our code examples (https://github.com/resendlabs/react-email/tree/main/examples) or live demo (https://github.com/resendlabs/react-email/tree/main/apps/demo)?

**Comment by grmatthews** [comment]
This is a bit frustrating.
I can see you're trying to help but you and your team are seriously lacking comprehension skills.
The main points
- Yes I have looked at your examples
- Yes I created a sandbox and my simple implementation of your library DID work in the sandbox but then something happened and for some unknown reason my sandbox rolled back to a prior version. The point being that this seemed to indicate the error I reported was a problem with my environment. I told you this but for some unknown reason you still tried to run the sandbox as if this was somehow still relevant. I was not able to replicate the error in the sandbox at any point.
- I specifically asked if anyone knew perhaps what library or environment issues could cause the problem I was having, multiple times, and while this is still the issue no one was able to offer a comment on this. And if not, that's fine but not sure why you guys kept trying to offer advice on the above points when they're not relevant.

**Comment by grmatthews** [comment]
This is the point - I cannot reproduce it outside of my environment, so I wanted to get help from a general point of view in Node modules on what might cause the error I reported. The runtime has a problem with something, and I was asking to see if anyone had ideas on what could cause this, i.e. take some guesses without being able to reproduce it -- because I can't
