### ISSUE TITLE
Sendgrid sending only text not html

### ISSUE THREAD

**Issue by kehindeegunjobi93** [resendlabs/react-email#490]
Hi,

When I try to send an email. I get the error from SendGrid that says `Unless a valid template_id is provided, the content parameter is required. There must be at least one defined content block. We typically suggest both text/plain and text/html blocks are included, but only one block is required.`

So I added text to the options object like this
  const options = {
    from: 'support@email.com',
    to: userEmail,
    subject,
    html: htmlTemplate,
   text: text
  };

But whenever I do this, The email I get is displayed as text not HTML. Is there any way around this?

**Comment by bukinoshita** [comment]
What's the content of `htmlTemplate` and `text`?

**Comment by kehindeegunjobi93** [comment]
I was told its a sendgrid issue and not ReactEmail. So I'll be closing this down.
