### ISSUE TITLE
Usage with Next.js Api Routes

### ISSUE THREAD

**Issue by alvarlagerlof** [resendlabs/react-email#493]
Hi! I'm trying to render an email inside a Next.js api route.

My fine in `/api/email.tsx` looks something like: 

```tsx
import React from 'react'
import { Button } from '@react-email/button'
import { Html } from '@react-email/html'
import { render } from '@react-email/render'

export const runtime = 'edge'

function Component() {
  return (
    <Html>
      <Button
        pX={20}
        pY={12}
        href="https://example.com"
        style={{ background: '#000', color: '#fff' }}
      >
        Click me
      </Button>
    </Html>
  )
}

export default function test(request: Request) {
  const text = render(<Component />)
  return new Response(text)
}
```

I get this kind of error:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/14835120/220215605-f20b0b77-1001-4314-995e-365a01e8be4c.png">

Is there anything I could do? I'd really like to render inside my current project.

**Comment by zenorocha** [comment]
I don't believe this will work as an Edge runtime. Can you use this as a regular API endpoint instead?

```js
export const runtime = 'edge'
```

**Comment by alvarlagerlof** [comment]
You were totally right. All seems to ber working well now! I'd be nice to be able to use it on the Edge runtime but I think that's a React/Vercel issue.

**Comment by alvarlagerlof** [comment]
> I don't believe this will work as an Edge runtime. Can you use this as a regular API endpoint instead?

I think I was just able to make it work using the edge runtime. I took the `render` function in @react-email/render which was nice and short, and replaced renderToStaticMarkup with `renderToReadableStream`. 

Streaming itself is not actually important for email, and react-email had the two tweaks (doctype and pretty formatting), so I converted the stream back to a string and then I was able to use the whole thing in the Edge Runtime on Vercel, and https://wintercg.org/ would work in general.

I'm getting response times around 50-200ms depending on how warm it it is (first is a little slower). I think this would be interesting to have build in to react-email @zenorocha. What do you think?

**Comment by mkreuzmayr** [comment]
@zenorocha 

I just built a similar solution as @alvarlagerlof. My implementation checks if `renderToStaticMarkup` is defined. If not `renderToReadableStream` is used and the stream is converted to a string.

It would be nice to have something like this directly integrated in react-email, but it requires the introduction of an async function like `renderAsync` to work, so we are not introducing breaking change. I could create a pull request with my changes and add it to the docs if you are ok with creating a `renderAsync` function.

**Comment by thosmos** [comment]
> @zenorocha
>  I could create a pull request with my changes and add it to the docs if you are ok with creating a `renderAsync` function.

I just ran into this problem and it would be great to see your workaround and yes please make a PR.

**Comment by mkreuzmayr** [comment]
I will create a PR this weekend, hope it gets attention. I'll reply here after I opened it.

**Comment by mkreuzmayr** [comment]
PR filed at https://github.com/resendlabs/react-email/pull/603
