### ISSUE TITLE
Media queries support

### ISSUE THREAD

**Issue by kowalczyk-mateusz** [resendlabs/react-email#494]
Hi, will @Media queries be supported? Because as I can see in caniemail it is supported in most web/mobile email clients.

**Comment by bukinoshita** [comment]
Yup, can you share what are you trying to do?

**Comment by kowalczyk-mateusz** [comment]
I want to have two columns on desktop, and one column on mobile (when width is lower than 400) and I also want to have different padding on mobile and different on desktop.

**Comment by galnir** [comment]
> I want to have two columns on desktop, and one column on mobile (when width is lower than 400) and I also want to have different padding on mobile and different on desktop.

did you manage to get it working?

**Comment by kowalczyk-mateusz** [comment]
I changed my layout, to have one column on both devices, but now i guess you can use tailwind for media queries :)

**Comment by kowalczyk-mateusz** [comment]
> > I want to have two columns on desktop, and one column on mobile (when width is lower than 400) and I also want to have different padding on mobile and different on desktop.
> 
> did you manage to get it working?


I changed my layout, to have one column on both devices, but now i guess you can use tailwind for media queries :)

**Comment by kasapvictor** [comment]
> > > I want to have two columns on desktop, and one column on mobile (when width is lower than 400) and I also want to have different padding on mobile and different on desktop.
> > 
> > 
> > did you manage to get it working?
> 
> I changed my layout, to have one column on both devices, but now i guess you can use tailwind for media queries :)

The use of <styles>tailwind styles...</styles> in your email template is not supported by browsers like gmail.com

**Comment by kowalczyk-mateusz** [comment]
> > > > I want to have two columns on desktop, and one column on mobile (when width is lower than 400) and I also want to have different padding on mobile and different on desktop.
> > > 
> > > 
> > > did you manage to get it working?
> > 
> > 
> > I changed my layout, to have one column on both devices, but now i guess you can use tailwind for media queries :)
> 
> The use of `<styles>tailwind styles...</styles>` in your email template is not supported by browsers like gmail.com

That's why i changed my layout to consist of only one column on both devices, because you never know if what email client is customer using
