### ISSUE TITLE
Error: read properties of undefined 

### ISSUE THREAD

**Issue by Alex001213** [resendlabs/react-email#499]
I create a new template using `npx create-email@latest`, then `npm install`  `npm run export`, but it raised error, is it a bug or my mistake?

```
  loginCode = "sparo-ndigo-amurt-secan"
  ^

TypeError: Cannot read properties of undefined (reading 'loginCode')
    at Object.Email (/home/user/test/react-email-starter/out/notion-magic-link.js:3904:3)
    at exportTemplates (/home/user/test/react-email-starter/node_modules/react-email/dist/source/commands/export.js:61:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

> environment
react-email 1.7.13
npm version 9.5.0 
node version 18.12.1

**Comment by lfirek** [comment]
@Alex001213 The workaround for this error is to create a wrapper that check props are defined.

```
export default function EmailWrapper(props) {
  return Email(props || {})
}

function Email({...
...
```

**Comment by bukinoshita** [comment]
hmmm, interesting. Thanks for the workaround, this should be a simple fix.

**Comment by heysujal** [comment]
@lfirek I am facing the same error. How to fix it? How do I implement this workaround?
