### ISSUE TITLE
Font component is not working as expected

### ISSUE THREAD

**Issue by akosipc** [resendlabs/react-email#501]
## Expected Results
- I was expecting that the Font component would provide a easier way to use fonts. Right now, it's not working without editing the values in the browser.

## Steps to reproduce
- Install `@react-email/fonts` or `@react-email/components@latest`
- Include the example from the package:
```jsx
const Email = () => {
  return (
    <Html lang="en">
      <Head>
        <Font
          fontFamily="Roboto"
          fallbackFontFamily="Verdana"
          webFont={{
            url: 'https://fonts.gstatic.com/s/roboto/v27/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2',
            format: 'woff2',
          }}
        />
      </Head>
    </Html>
  );
};
```
- Start the email dev server and preview the sample e-mail
- Check for font-face styles from the browser console. All single quotes are converted to their hex code values (`&#x27;`). For more info, please refer to the screenshots in the next section

#### font-face with hexcode values
[![Image from Gyazo](https://i.gyazo.com/b5bf354f2752ace0ebd28bc09247a695.gif)](https://gyazo.com/b5bf354f2752ace0ebd28bc09247a695)

#### font-face with non-hexcode values. Manually removed
[![Image from Gyazo](https://i.gyazo.com/4873f56e974b932bab29261e3465a893.png)](https://gyazo.com/4873f56e974b932bab29261e3465a893)

**Comment by akosipc** [comment]
Hello, update on this. I've tried to make a custom component with the code below and it works properly.

```jsx
const Font = ({ 
    webFont,
    fontStyle = 'normal',
    fontFamily,
    fontWeight = 400,
    fallbackFontFamily,
}) => {
    const src = webFont ? `src: url(${webFont.url}) format(${webFont.format});` : "";

    return (
        <style>
        {
            `
            @font-face {
                font-style: ${fontStyle};
                font-family: ${fontFamily};
                font-weight: ${fontWeight};
                mso-font-alt: ${Array.isArray(fallbackFontFamily) ? fallbackFontFamily[0] : fallbackFontFamily};
                ${src}
            }

            * {
                font-family: ${fontFamily}, ${Array.isArray(fallbackFontFamily) ? fallbackFontFamily.join(", ") : fallbackFontFamily};
            }
            `
        }
        </style>
    )
}
```

**Comment by furkanbay** [comment]
> Hello, update on this. I've tried to make a custom component with the code below and it works properly.
> 
> ```js
> const Font = ({ 
>     webFont,
>     fontStyle = 'normal',
>     fontFamily,
>     fontWeight = 400,
>     fallbackFontFamily,
> }) => {
>     const src = webFont ? `src: url(${webFont.url}) format(${webFont.format});` : "";
> 
>     return (
>         <style>
>         {
>             `
>             @font-face {
>                 font-style: ${fontStyle};
>                 font-family: ${fontFamily};
>                 font-weight: ${fontWeight};
>                 mso-font-alt: ${Array.isArray(fallbackFontFamily) ? fallbackFontFamily[0] : fallbackFontFamily};
>                 ${src}
>             }
> 
>             * {
>                 font-family: ${fontFamily}, ${Array.isArray(fallbackFontFamily) ? fallbackFontFamily.join(", ") : fallbackFontFamily};
>             }
>             `
>         }
>         </style>
>     )
> }
> ```
> 
> I've removed all single quotes from the Font component.

thanks it worked for me.

**Comment by bukinoshita** [comment]
I think this is related to https://github.com/resendlabs/react-email/issues/442, right?

**Comment by akosipc** [comment]
@bukinoshita Yes, I do believe it is related.

**Comment by nishant23122000** [comment]
Do you have any updates on this? I know I can create a Custom Font component but why is `@react-email/font` not working?

**Comment by appledesire** [comment]
I found a similar issue.
The outlook email has wrong css.
How should I manage this?

**Comment by bighoho123** [comment]
Same issue here.

**Comment by thiagonzalez** [comment]
> Hello, update on this. I've tried to make a custom component with the code below and it works properly.
> 
> ```js
> const Font = ({ 
>     webFont,
>     fontStyle = 'normal',
>     fontFamily,
>     fontWeight = 400,
>     fallbackFontFamily,
> }) => {
>     const src = webFont ? `src: url(${webFont.url}) format(${webFont.format});` : "";
> 
>     return (
>         <style>
>         {
>             `
>             @font-face {
>                 font-style: ${fontStyle};
>                 font-family: ${fontFamily};
>                 font-weight: ${fontWeight};
>                 mso-font-alt: ${Array.isArray(fallbackFontFamily) ? fallbackFontFamily[0] : fallbackFontFamily};
>                 ${src}
>             }
> 
>             * {
>                 font-family: ${fontFamily}, ${Array.isArray(fallbackFontFamily) ? fallbackFontFamily.join(", ") : fallbackFontFamily};
>             }
>             `
>         }
>         </style>
>     )
> }
> ```
> 
> I've removed all single quotes from the Font component.

Thank you so much for this! It worked when I tried to import just one Font, but when I tried to import 3 weights of the same font, just the first one was loaded. Do you know why? Is anybody here with the same issue?

```
    <Html lang="en">
      <Head>
        <Font
          fontFamily="Poppins"
          fallbackFontFamily="Arial"
          webFont={{
            url: "https://fonts.gstatic.com/s/poppins/v20/pxiEyp8kv8JHgFVrJJnecnFHGPezSQ.woff2",
            format: "woff2",
          }}
        />

        <Font
          fontFamily="Poppins"
          fallbackFontFamily="Arial"
          webFont={{
            url: "https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLEj6Z11lFd2JQEl8qw.woff2",
            format: "woff2",
          }}
          fontWeight={600}
        />

        <Font
          fontFamily="Poppins"
          fallbackFontFamily="Arial"
          webFont={{
            url: "https://fonts.gstatic.com/s/poppins/v20/pxiByp8kv8JHgFVrLCz7Z1xlFd2JQEk.woff2",
            format: "woff2",
          }}
          fontWeight={700}
        />
      </Head>
  </Html>
```

**Comment by bukinoshita** [comment]
Can we try with the new version? https://github.com/resendlabs/react-email/pull/701 should fix this

**Comment by vishnup-ditto** [comment]
Hey @bukinoshita I am on `v1.9.4` which I believe is the latest version. Still seems to be an error for me. I get 
![image](https://github.com/resendlabs/react-email/assets/113330036/f9738ffe-59d3-4785-bcc9-68f6198c601e)

I assume these are HTML entities somehow attaching to the font-family style?

**Comment by Hexi1997** [comment]
same

**Comment by iRajatDas** [comment]
Issue still persists

**Comment by PPraneesh** [comment]
```
 <Head>
        <style>
          {
            `
            @import url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap');
            *{
            font-family: 'Inter', sans-serif;
            }`
          }
        </style>
</Head>
```

try this.. it is working for me..

**Comment by rryyqn** [comment]
Still have the same issue.
