### ISSUE TITLE
Enable conventional use of tables

### ISSUE THREAD

**Issue by morgs32** [resendlabs/react-email#503]
I'd like to be able to render a more "conventional" use of tables such as this:

![image](https://user-images.githubusercontent.com/1364795/221283454-d94da570-5ad7-4fc3-a751-37263058bf40.png)

Which means I'd like to create `tr` components in a single `table` component. That way columns are the same width. And I can use an empty `td` on the bottom left when providing a summation line.

Thoughts?

**Comment by bukinoshita** [comment]
You can use default HTML tags + our react-email components just fine, you're not tied to only using our components. So you can combine the two if you want.

Example:

```tsx
<Body>
  <Container>
    <table>
      <tr>
        ...
     </tr>
  </Container>
</Body>
```

**Comment by morgs32** [comment]
Yea that's what I'm doing. Think this warrants a feature request? Let me know and I'll write up something more complete in a separate issue.

**Comment by YousefED** [comment]
> You can use default HTML tags + our react-email components just fine, you're not tied to only using our components. So you can combine the two if you want.


@bukinoshita isn't one of the benefits of React Email that it streamlines components for consistent rendering across email clients? If I opt-in to using a default HTML tag (like `table` in your example), I'd miss attributes / styling info to have the best compatibility, correct? This would mean I'd need to add these attributes myself (and research what's needed for best compatibility). 

MJML does implement a table element which implements these attributes (see [here](https://mjml.io/try-it-live/components/table)). Does react-email follow a different philosophy, or has this just not been implemented yet?

**Comment by gabrielmfern** [comment]
@YousefED Looking at the output from `mj-table` it seems very similar to our `Section`'s and `Row`'s. You should pretty much get similar possible outputs/use cases. 

But, to clarify, letting users simply use a table is very powerful, as a component can only go so far, and being able to use a table in any way you want can lead to users building their own custom components like https://github.com/codeskills-dev/responsive-email
