### ISSUE TITLE
Process of local development

### ISSUE THREAD

**Issue by OlegGulevskyy** [resendlabs/react-email#504]
Hi,
Library looks great!
I wonder, what is the process of working with the library locally, after the fork?
I have cloned the `react-email` library and have my `react-email-started` folder with all my emails.
I am trying to play around with `@react-email/render` package. I have tried creating a `npm link` symlink but, while seeing the symlink in my `node_modules`, I can't get the changes appear in the `react-email-started`.
So, what I did is:
1. In folder `@react-email/render` run `npm link`
2. In `react-email-starter` folder run `npm link @react-email/render` to create a symlink with the local package
3. Run `yarn dev` in `@react-email/render` folder to watch the changes and rebuild the package
4. Create a dummy function in file `render.ts` and export it (in my case, called it `renderToScriplets`)
5. Head over to `react-email-starter` and run `yarn dev`, while `node_modules` seems to have correct changes, and the `index.js/mjs/d.ts` are updated, importing function is not possible, where webpack is not aware of the changes made.
```
TypeError: (0 , _react_email_render__WEBPACK_IMPORTED_MODULE_9__.renderToScriplets) is not a function
    at eval (webpack-internal:///./emails/file-generated.tsx:167:84)
....
```
Would appreciate any advice on what am I missing or doing wrong?

**Comment by OlegGulevskyy** [comment]
Command `yarn export` works as intended though, I can see the changes and can work with them that way

**Comment by bukinoshita** [comment]
Yeah, `npm link` it's a bit tricky and sometimes works. I've using [yalc](https://github.com/wclr/yalc) lately to test a few things locally. Can you give that a try?
