### ISSUE TITLE
Dark mode support with tailwindcss

### ISSUE THREAD

**Issue by Brettm12345** [resendlabs/react-email#509]
Styles using the dark mode variant should use a dark mode media query

**Comment by mohitmohlia** [comment]
Hi, can you assign this to me ?

**Comment by eivindml** [comment]
Any planned work on this? Would be really cool!

**Comment by gabrielmfern** [comment]
> ark mode media query

you mean classes that have `dark:*`?

**Comment by mateogalic112** [comment]
Any updates on this? It is still not applying dark mode classes 😓

**Comment by gabrielmfern** [comment]
The newest stable version should have this issue fixed everyone, please try out `@react-email/tailwind@0.0.13` or the latest for components and if you still experience this issue please tell me and I'll reopen it.
