### ISSUE TITLE
Plans to create an alternative for vue?

### ISSUE THREAD

**Issue by mklueh** [resendlabs/react-email#510]
Hi there,

I love the idea of this project and I am looking for a while now for such a thing for Vue. 

Are there any plans to create such a package as well?

**Comment by bukinoshita** [comment]
> Hi there,
> 
> I love the idea of this project and I am looking for a while now for such a thing for Vue.
> 
> Are there any plans to create such a package as well?

We would love to support vue, but we want to nailed down with react first.
