### ISSUE TITLE
Dev server left running when preview app crashes

### ISSUE THREAD

**Issue by mckelveygreg** [resendlabs/react-email#511]
Hey! Super excited about this project!
I noticed that when the dev server crashes (node errors, etc), the next server is still running on port 3000 and I get the error `Port 3000 is already in use.` My work around at this point is to just nuke every node process running and then i'm able to restart the server. Is there a more graceful way to handle this?

**Comment by bukinoshita** [comment]
@mckelveygreg What's the best way to reproduce this?

**Comment by mckelveygreg** [comment]
Oh of course, my bad.
In my work flow, I find the bug by:
- start dev server
- remove image asset that was copied over
- get error: `throw new Error(`Something went wrong while copying the file to ${constants_1.PACKAGE_EMAILS_PATH}, ${result.cat()}`);`
- try to start dev server
- get error: `Port 3000 is already in use.`
