### ISSUE TITLE
email export with Tailwind: Could not resolve "@tailwindcss/oxide"

### ISSUE THREAD

**Issue by mckelveygreg** [resendlabs/react-email#512]
When using the `email export` command with an email including the `<Tailwind />` component, I get the following error: `Could not resolve "@tailwindcss/oxide"`.

However, it seems to work fine with the `render` method from `@react-email/render` 🤷 
and the dev server still works fine.

Versions:
```json
    "@react-email/preview": "0.0.5",
    "@react-email/render": "^0.0.6",
    "@react-email/tailwind": "0.0.5",
    "react": "^18.2.0",
    "react-email": "1.7.14"
```

**Comment by bukinoshita** [comment]
@vinicoder Any idea on this?

**Comment by IgnisDa** [comment]
I am getting the same error.

**Comment by vinicoder** [comment]
Hey guys! This is a package that Tailwind introduced in the latest versions, but I had already removed it from the build in `tw-to-css`, yet it seems to still be causing some error somehow. I'm investigating what's happening and should be back as soon as possible.

**Comment by chronark** [comment]
This also happens when importing it into a nextjs serverless function
however an app router RSC works fine

**Comment by bukinoshita** [comment]
Is this fixed? cc @vinicoder

**Comment by chronark** [comment]
works for me :)

**Comment by vinicoder** [comment]
> Is this fixed? cc @vinicoder 

It should work as I removed this module `@tailwind/oxide` from the `tw-to-css` package in my last PR (mentioned here, which was already merged). 🙃
