### ISSUE TITLE
Tailwind styles not catching / (forward slash) and . (period)

### ISSUE THREAD

**Issue by mckelveygreg** [resendlabs/react-email#518]
When I try and use `w-1/2` or `p-3.5`, those classes don't seem to picked up and put in the head. 
My regex isn't wonderful, but I don't think i see those symbols in the few places they are being checked in https://github.com/resendlabs/react-email/blob/c8ccc07de7e9f859d680e1adfeaa221d9dd0d6ba/packages/tailwind/src/tailwind.tsx

**Comment by vinicoder** [comment]
Nice @mckelveygreg! Tested here, and it looks like it's working correctly. I would only add tests for the inline method too. I saw that you put a div without a responsive style, but when it is detected, every class goes to the head, so it can't test inline styles. Like this:

```js
it('should replace percent signs with underscore in both class name and selector using inline method', () => {
  const actualOutput = render(
    <Tailwind>
      <html>
        <head />
        <body>
          <div className="w-[50%]" />
        </body>
      </html>
    </Tailwind>,
  );
  expect(actualOutput).toMatchInlineSnapshot(
    `"<html><head></head><body><div style=\\"width:50%\\"></div></body></html>"`,
  );
});
```

But I'd merge it, as it's working correctly. cc: @bukinoshita @zenorocha

**Comment by mckelveygreg** [comment]
Oh my, I'm not sure if anything changed in the last few weeks, but I wasn't able to get the project running anymore. I was running into missing packages and issues of the `utils` stuff not being found? 

I guess I could add those tests once local dev seems to stabilize again?
