### ISSUE TITLE
Invalid CSS declarations in compiled inline styles

### ISSUE THREAD

**Issue by morellodev** [resendlabs/react-email#524]
Hi,

I see that, when using style props like `pX` or `pY`, they are correctly converted to `padding: y x` but the compiled inline styles also includes invalid `p-x` and `p-y` declarations:

<img width="1565" alt="SCR-20230306-dmg" src="https://user-images.githubusercontent.com/19588613/223061339-e4262afc-9c45-43a1-8284-7471de6ea9bb.png">

Awesome project btw!

**Comment by betty-alagwu** [comment]
Hello @bukinoshita  i will love to work on this, can i take this on?

**Comment by bukinoshita** [comment]
> Hello @bukinoshita  i will love to work on this, can i take this on?
> 
> 

Yes, feel free to take

**Comment by betty-alagwu** [comment]
Thanks very much. I had some trouble setting up the project repository. So I left a message on the General channel on Discord. Could you please have a look and share some feedback ? Thank you very much and sorry for the trouble.

**Comment by NiazMorshed2007** [comment]
@bukinoshita is it open? I would like to take a shot
