### ISSUE TITLE
Error: AnimateSharedLayout is deprecated

### ISSUE THREAD

**Issue by bernhardw** [resendlabs/react-email#552]
Hello,

I use react-email in a Next.js project with the latest framer-motion installed.
When I run `email dev`, I receive the following error on http://localhost:3000:

> Unhandled Runtime Error
> Error: AnimateSharedLayout is deprecated: https://www.framer.com/docs/guide-upgrade/##shared-layout-animations
> Call Stack
> invariant
> node_modules/framer-motion/dist/es/utils/errors.mjs (13:0)
> eval
> node_modules/framer-motion/dist/es/components/AnimateSharedLayout.mjs (9:17)
> [...]

`AnimateSharedLayout` is used by react-email for its preview.

Strangely enough, when I check the version of framer-motion inside `.react-email/package.json`, it gets overwritten to the newest version used by my own Next.js app inside the project roots package.json.

When I manually set the version back to `8.4.6` in `.react-email/package.json` and run npm install && npm update in my project root, the specified version gets rewritten to the one from my own project.

The same behavior seems to be happening with any other package thats used by react-email and my project.

Any ideas?

**Comment by bukinoshita** [comment]
Can you double check if you're using the latest version of react email? We recently had a [PR](https://github.com/resendlabs/react-email/pull/523)that changed that

**Comment by bukinoshita** [comment]
Going to close since we didn't hear it back
