### ISSUE TITLE
Parameters are ignored

### ISSUE THREAD

**Issue by AngCosmin** [resendlabs/react-email#557]
Hey,

I just started to use this library today and I cannot make it work.

If I leave the default values for the parameters everything is fine, but if I try to add some custom values looks like they are not attached correctly to the start script. Check out the screenshot below. Looks like the port parameter is considered as path.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/8146514/226499400-3d858b2c-d83f-450d-bdc0-06ac256be973.png">

PS. I tried to delete the `.react-email` folder and I still get the same error

Please let me know if you need more details.

**Comment by dauletbaev** [comment]
Same for me downgrading version fixed the issue.

**Comment by rfoel** [comment]
Fixed in `1.8.0` #590
