### ISSUE TITLE
Website crashes

### ISSUE THREAD

**Issue by herbievine** [resendlabs/react-email#600]
### Describe the Bug

I've tried this on both Safari and Chrome (both up to date), and the website simply doesn't work...

`/overview`
![Screenshot 2023-03-23 at 12 18 55](https://user-images.githubusercontent.com/41120535/227188123-ea6c6a6a-3d8e-4306-b5f5-347d557faa9d.png)

`/emails`
![Screenshot 2023-03-23 at 12 19 07](https://user-images.githubusercontent.com/41120535/227188270-3955f8b6-63a7-46ff-a929-ce17111dbe2c.png)

### Which package is affected (leave empty if unsure)

web

### Link to the code that reproduces this issue

https://resend.com/emails

### To Reproduce

Jump on the website

### Expected Behavior

it loads

### What's your node version? (if relevant)

n/a

**Comment by bukinoshita** [comment]
Closing this issue since it's related to Resend and not React Email. But, thanks for reporting and just pushed a fix on this, feel free to use Resend support email (support@resend.com) or DM me on [Twitter](https://twitter.com/bukinoshita).
