### ISSUE TITLE
Button styles inconsistent

### ISSUE THREAD

**Issue by Rigel772** [resendlabs/react-email#621]
### Describe the Bug

For button styles:
```
const button = {
  backgroundColor: "#007ee6",
  borderRadius: "4px",
  color: "#fff",
  fontFamily: "'Open Sans', 'Helvetica Neue', Arial",
  fontSize: "15px",
  textDecoration: "none",
  textAlign: "center",
  display: "block",
  width: "210px",
  padding: "14px 7px",
};
```
In generated html I get:
```
<a href="https://dropbox.com" data-id="react-email-button" target="_blank" 
style="background-color:#007ee6;
border-radius:4px;color:#fff;
font-family:&#x27;Open Sans&#x27;, &#x27;Helvetica Neue&#x27;, Arial;font-size:15px;
text-decoration:none;
text-align:center;
display:inline-block;
width:210px;
padding:0px 0px;
line-height:100%;
max-width:100%">
```
Some styles are ok but padding is set to 0.

### Which package is affected (leave empty if unsure)

@react-email/button

### Link to the code that reproduces this issue

In example dropbox reset password template

### To Reproduce

Tested in DropboxResetPasswordEmail sample component.

### Expected Behavior

I expect the styles to be same as in styles object.

**Comment by Rigel772** [comment]
![image](https://user-images.githubusercontent.com/1696243/229900307-4fe758a4-f506-4d08-ad03-4a3292ba54c4.png)

**Comment by rfoel** [comment]
@Rigel772 for some reason buttons now have a different way to set paddings. You need to use `pY` and `pX`. Check [here](https://github.com/resendlabs/react-email/blob/main/packages/button/src/button.tsx#L7).

**Comment by Rigel772** [comment]
@rfoel Thanks a lot! Is it for button only?

**Comment by rfoel** [comment]
As far as I know it is.

**Comment by Rigel772** [comment]
@rfoel Thank you. Looks like Tailwind influence... it is worst than COVID ;)

**Comment by rfoel** [comment]
@Rigel772 I couldn't agree more 😂 
But I think it has something to do with email clients too, there's a `letter-spacing` and a `text-raise` fix for Outlook. I would've approach the workaround differently, instead of adding two new props ~and not documenting it~, I would try to extract the padding style from the style object itself and parse it.

**Comment by bukinoshita** [comment]
@rfoel Yeah, we didn't decided in which approach to go for it. If inline styles is fine or have styles defined by prop.
Would love to hear more thoughts, the button was the first "experiment" but only with padding.

https://github.com/resendlabs/react-email/discussions/576
