### ISSUE TITLE
Latest release error messages when running dev

### ISSUE THREAD

**Issue by pitops** [resendlabs/react-email#633]
### Describe the Bug

![Screenshot 2023-04-07 at 12 49 34 AM](https://user-images.githubusercontent.com/9624361/230500326-27926d3d-4f1b-448c-91a6-4168961bc540.png)

### Link to the code that reproduces this issue

.

### To Reproduce

Use latest release of `npx create-email`

### Expected Behavior

.

**Comment by EyMaddis** [comment]
Solved here: https://github.com/resendlabs/react-email/pull/615

**Comment by chetannn** [comment]
When this is going to be released ?

**Comment by bukinoshita** [comment]
Fixed and merged, just published a version
