### ISSUE TITLE
Error: Cannot find module './static'

### ISSUE THREAD

**Issue by pitops** [resendlabs/react-email#634]
### Describe the Bug

As the title says, when using latest `npx create-email` and then running `npm run dev`. Not touching anything

![Screenshot 2023-04-07 at 12 52 20 AM](https://user-images.githubusercontent.com/9624361/230500702-5050aa69-3ab2-4ed3-ad1c-6831e4da4e43.png)

![Screenshot 2023-04-07 at 12 52 37 AM](https://user-images.githubusercontent.com/9624361/230500733-a6034144-fb80-49b0-a6a1-182e19fdf001.png)

### Link to the code that reproduces this issue

.

### To Reproduce

.

### Expected Behavior

.

**Comment by stefanosandes** [comment]
As a workaround, you can move the `static` folder from emails to root directory.

**Comment by enesozturk** [comment]
As @stefanosandes suggested, moving /static to root works. This should be fixed in template with #640.

**Comment by bukinoshita** [comment]
Fixed on https://github.com/resendlabs/react-email/pull/658
