### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version ">=12.22.0 <=16.x.x". Got "18.12.1"

### ISSUE THREAD

**Issue by TelegramUsername** [resendlabs/react-email#635]
### Describe the Bug

when using `yarn create email` the following error is coming
```
PS D:\user\Coding\NextJS> yarn create email
yarn create v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error create-strapi-app@4.1.9: The engine "node" is incompatible with this module. Expected version ">=12.22.0 <=16.x.x". Got "18.12.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

### Link to the code that reproduces this issue

none

### To Reproduce

- Run
```bash
yarn create email
```

### Expected Behavior

to mkae a folder with name `react-email-starter`

### What's your node version? (if relevant)

18.12.1

**Comment by JorbFreire** [comment]
I tried to reproduce the error using the same node version but it performed the expected behavior.
More information would be appreciated.

**Comment by bukinoshita** [comment]
Going to close this for now, happy to revisit if we have more information.
