### ISSUE TITLE
tsconfig.json outside root repository affects `email export` behavior

### ISSUE THREAD

**Issue by iamchubko** [resendlabs/react-email#639]
### Describe the Bug

If react-email folder is inside a project with tsconfig.json, when you use `npx email export` in the react-email folder:
1. output in `out` same structure as in `emails` folder, but `js` files and with about 20k lines of code each
2. Infinite `⠇ Preparing files...` in the console

### Which package is affected (leave empty if unsure)

create-email

### Link to the code that reproduces this issue

Repro is enough

### To Reproduce

1. `npx create-email@latest` in another folder
2. create `tsconfig.json` in the outer folder with the following content
```json
{
  "compilerOptions": {
    "jsx": "preserve",
  },
}
```

Final structure should look something like this
```
outer-folder/
├─ react-email-starter/
├─ tsconfig.json
```

### Expected Behavior

`npx email export` should behave as usual

**Comment by ipenywis** [comment]
I'm having the same issue. I had to create a separate project for react-email

**Comment by shaunsaker** [comment]
Just ran into this issue and as a temporary workaround, you could temporarily "hide" the outer `tsconfig.json` with:

```
mv ../tsconfig.json ../tsconfig_temp.json && yarn export && ../mv tsconfig_temp.json ../tsconfig.json
```

**Comment by MicahLyle** [comment]
I also noticed that having `"type": "module"` in `package.json` makes `email export` crash like this:

```
> email export -p --outDir ./emails/exported

✔ Preparing files...

⠋ rendering example.jsnode:internal/validators:95
      throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received an instance of Error
    at process.set [as exitCode] (node:internal/bootstrap/node:124:9)
    at Object.exit (node:internal/process/per_thread:188:24)
    at process.<anonymous> (C:\Users\micah\core\proj\et\dsk\dsk\node_modules\react-email\dist\source\utils\start-server-command.js:43:27)
    at process.emit (node:events:511:28)
    at process.processEmit [as emit] (C:\Users\micah\core\proj\et\dsk\dsk\node_modules\signal-exit\index.js:199:34)
    at process._fatalException (node:internal/process/execution:159:25)
    at processPromiseRejections (node:internal/process/promises:289:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.2.0
```

**Comment by coreybruyere** [comment]
@MicahLyle I don't have "type": "module" defined in package.json but am getting this same error? Any other thought on how to resolve that when attempting to export?

**Comment by MicahLyle** [comment]
@coreybruyere I explicitly specified `"type": "commonjs"` to resolve it...

If that doesn't work then I never ran into it outside of that so not sure.
