### ISSUE TITLE
Can't install with npm (No matching version found for @react-email/components@0.0.6)

### ISSUE THREAD

**Issue by pavelrahman619** [resendlabs/react-email#643]
### Describe the Bug

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @react-email/components@0.0.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

This occurs during npm install.

Using Node Version 16.13.1 (Currently using 64-bit executable)

### Which package is affected (leave empty if unsure)

@react-email/components

### Link to the code that reproduces this issue

https://github.com/pavelrahman619/react-email-starter

### To Reproduce

npx create-email@latest
npm install

### Expected Behavior

npm install runs successfully.

### What's your node version? (if relevant)

16.13.1 (Currently using 64-bit executable)

**Comment by graywolf336** [comment]
I got the same issue. Running `npx create-email@latest` and then `yarn` inside results in `v0.0.6` of `@react-email/components` not being found.

**Comment by pavelrahman619** [comment]
> I got the same issue. Running `npx create-email@latest` and then `yarn` inside results in `v0.0.6` of `@react-email/components` not being found.
> 
> Looks like this is a duplicate of: #632 And a patch has been created: #640

Yes doing this worked thanks.

**Comment by bukinoshita** [comment]
Fixed and merged!
