### ISSUE TITLE
Tailwind component: error for when there is no <head> or <html> is very unclear

### ISSUE THREAD

**Issue by andr-ec** [resendlabs/react-email#666]
### Describe the Bug

While adding the plugin daisyui to a config like It gives an error on opening the component. I'm not sure if plugins are not supported or there is another issue going on. 

```
Server Error
Error: Tailwind: To use responsive styles you must have a <html> and <head> element in your template.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
src/app/preview/[slug]/page.tsx (27:23) @ render

  25 | 
  26 | const Email = (await import(`../../../../emails/${params.slug}`)).default;
> 27 | const markup = render(<Email />, { pretty: true });
     |                     ^
  28 | const plainText = render(<Email />, { plainText: true });
  29 | const basePath = pathJoin(process.cwd(), CONTENT_DIR);
  30 | const path = pathJoin(basePath, template[0]);
```

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://github.com/andr-ec/emailrepro

### To Reproduce

`yarn add daisyui`
create this component: 
```
import {
  Body,
  Button,
  Container,
  Column,
  Head,
  Heading,
  Html,
  Img,
  Preview,
  Row,
  Section,
  Text,
} from '@react-email/components';
import * as React from 'react';
import { Tailwind } from '@react-email/tailwind';

export default () => {
  return (
    <Html>
      <Head>
        <title>My email title</title>
      </Head>
      <Tailwind
        config={{
          plugins: [require("daisyui")],
          corePlugins: { container: false },
          daisyui: {
            styled: true,
            themes: false,
            base: false,
            utils: false,
            logs: false,
            rtl: false,
            prefix: "",
            darkTheme: "dark",
          },
          theme: {
            extend: {
              colors: {
                brand: '#007291',
              },
            },
          },
        }}
      >
        <Button
          href="https://example.com"
          className="btn btn-primary"
        >
          Click me
        </Button>
      </Tailwind>
    </Html>
  );
};
```

### Expected Behavior

The plugin will be loaded and used for styling.

### What's your node version? (if relevant)

16.20.0

**Comment by fkapsahili** [comment]
What I noticed is that you have to wrap your entire `Html` tag in the `Tailwind` element to make tailwind breakpoints work:

```javascript
    <Tailwind>
      <Html>
        <Head />
        <Body>
         {/** Rest of your code */}
```

**Comment by qedr** [comment]
> What I noticed is that you have to wrap your entire `Html` tag in the `Tailwind` element to make tailwind breakpoints work:
> 
> ```js
>     <Tailwind>
>       <Html>
>         <Head />
>         <Body>
>          {/** Rest of your code */}
> ```
> 
> Maybe this helps!

This fixes the original issue 🙏
However, creates a new warning:
`Warning: validateDOMNesting(...): <html> cannot appear as a child of <div>.
    at html
    at Tailwind (webpack-internal:///./node_modules/@react-email/tailwind/dist/index.mjs:16:19)`

**Comment by renatarko** [comment]
That's worked! ✅

**Comment by renatarko** [comment]
That's worked! ✅

**Comment by shellscape** [comment]
This would be an awesome addition to the documentation!

**Comment by jwarykowski** [comment]
> > What I noticed is that you have to wrap your entire `Html` tag in the `Tailwind` element to make tailwind breakpoints work:
> > ```js
> >     <Tailwind>
> >       <Html>
> >         <Head />
> >         <Body>
> >          {/** Rest of your code */}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe this helps!
> 
> This fixes the original issue 🙏 However, creates a new warning: `Warning: validateDOMNesting(...): <html> cannot appear as a child of <div>. at html at Tailwind (webpack-internal:///./node_modules/@react-email/tailwind/dist/index.mjs:16:19)`

@bukinoshita / @zenorocha - is anyone fixing the warning above? Doesn't look this has been raised in issues as of yet. Just a pain when running unit tests 😢

**Comment by Crateros** [comment]
Putting <Tailwind> at the top layer did not fix the issue for me, <Tailwind> needed to be directly above <Head /> but underneath the initial <Html> component.

**Comment by thesaltygerman** [comment]
@tmcw I try to work but no. the jsx-email has no require on child no error, is better for the tainwind

**Comment by lucassarcanjo** [comment]
I had the same issue with a published Next.js app. After upgrading `react-email` to `2.1.1` and `@react-email/components` to `0.0.16`, it's working fine.

**Comment by Marholoubek** [comment]
Only upgrading to the latest `@react-email/components` fixed it for me.
