### ISSUE TITLE
Broken CLI dev usage on Windows

### ISSUE THREAD

**Issue by changesbyjames** [resendlabs/react-email#667]
### Describe the Bug

When running on Windows (not WSL) the functionality that generates the `/emails` directory in the generated next app fails due to a regression that I believe was introduced here: https://github.com/resendlabs/react-email/commit/20344e6081dbe134c2f0913d08f04605f2a9f3e4.

The use of the glob library introduces a mixture of path formats that causes it to never find any files in that directory and if it did, it would fail because the output format is wrong for Windows.

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

The default starter that is generated using npx create-email@latest is failing.

### To Reproduce

Attempt to run `npx create-email@latest` on a Windows machine using the default environments. 

### Expected Behavior

The folder is a successfully created and populated with references to the emails.

**Comment by changesbyjames** [comment]
I have confirmed that downgrading to 1.9.0 has fixed the issue for me.

**Comment by iisalazar** [comment]
@changesbyjames what specifically did you downgraded?

**Comment by changesbyjames** [comment]
@iisalazar I downgraded 'react-email' to '1.9.0' - I don't know if the issue is present in 1.9.1.

**Comment by 3kumar** [comment]
The "email dev" cli is broken for version 1.9.3 on windows. Although it works fine on mac. I downgraded the version to 1.9.0 and it works.

**Comment by kno-raziel** [comment]
Experiencing same issue, so sad because I wanted to try this package

**Comment by PeterGKafkakis** [comment]
Just recently started having issues on windows as well, tried version 1.9.0 and getting this error

Desktop\react-email-starter\node_modules\commander\index.js:471
  var parsed = this.parseOptions(this.normalize(argv.slice(2)));

**Comment by heggland** [comment]
Running 1.9.3 in WSL works.. but awfully slow on first load.
Sometimes the compiler go crazy printing to the console until page is refreshed.
`event - compiled client and server successfully in 1498 ms (262 modules)
wait  - compiling...
event - compiled client and server successfully in 616 ms (262 modules)
wait  - compiling /page (client and server)...
event - compiled client and server successfully in 4.6s (1352 modules)
wait  - compiling...
event - compiled successfully in 780 ms (734 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 2.7s (1330 modules)
`

**Comment by EyMaddis** [comment]
I basically had to fix this blind. I would appreciate if somebody could test this:
https://github.com/resendlabs/react-email/pull/688

it should be resolved by this :)
