### ISSUE TITLE
DisplayName is missing for Column

### ISSUE THREAD

**Issue by saas-developer** [resendlabs/react-email#737]
### Describe the Bug

Column.displayName = "Column" is missing for the Column component

### Link to the code that reproduces this issue

https://github.com/resendlabs/react-email/blob/main/packages/column/src/column.tsx#L21

### To Reproduce

Please look at Column.tsx source code.

### Expected Behavior

Column.displayName = "Column" is added to the Component

**Comment by iampaandey** [comment]
can please assign tis issue to me?

**Comment by bukinoshita** [comment]
It's done on https://github.com/resendlabs/react-email/pull/739
