### ISSUE TITLE
`export` command swallows errors

### ISSUE THREAD

**Issue by hasparus** [resendlabs/react-email#803]
### Describe the Bug

Whenever an error is thrown during `export`, the error message is not printed to the user.

<img width="489" alt="image" src="https://github.com/resendlabs/react-email/assets/15332326/2c1f5f1c-7898-475b-b645-d52bd03dcb54">

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/new-bush-cd6cht?file=%2Femails%2FDemo_Receipt.tsx%3A5%2C3

### To Reproduce

Throw an error in a component or take a look at my repro: https://codesandbox.io/p/sandbox/new-bush-cd6cht?file=%2Femails%2FDemo_Receipt.tsx%3A5%2C3

### Expected Behavior

I worked around it by adding a try-catch with a console.error and a rethrow in `export` command.

**Comment by lordelogos** [comment]
HI @hasparus,

I think a better description will be

"_Whenever an errror is thrown during `export`, the error message is not printed to the user and it remains stuck in the "preparing files..." stage without providing any feedback to the user_"

That is the problem you are referring to if I understand you clearly.

**Comment by kevb10** [comment]
This led me down to many rabbit holes. Thanks for pointing this out. Confirmed as an issue. For me it's

`ReferenceError: React is not defined`

**Comment by mvdve** [comment]
Same issue here. Export is stuck on `Preparing files...` where the underlying problem is `React is not defined`

**Comment by coreybruyere** [comment]
When cloning the project and testing with SendGrid SDK I get stuck on "⠼ Preparing files..." when attempting to export.

**Comment by TomasSestak** [comment]
this is still hapenning

**Comment by gabrielmfern** [comment]
Can you maybe elaborate more on this @TomasSestak? 
The original problem with esbuild errors not being given as feedback were solved and should not be happening
anymore. Would be awesome if you give any kind of reproduction too, thanks!

**Comment by TomasSestak** [comment]
@gabrielmfern oh maybe this was because i was forced to use 0.0.18 because of some other issue. So maybe it is fixed in 0.0.19?

**Comment by gabrielmfern** [comment]
> @gabrielmfern oh maybe this was because i was forced to use 0.0.18 because of some other issue. So maybe it is fixed in 0.0.19?

Are you talking about create-email versions? If so, yeah the `0.0.18` sets up using an older version of the `react-email` CLI which could have persisted the problem for you. And the latest `0.0.19` had a regression we fixed and are still trying to find time to publish the fix on npm as well.
