### ISSUE TITLE
`email build` always fails if use .tsx extension

### ISSUE THREAD

**Issue by RanolP** [resendlabs/react-email#883]
### Describe the Bug

When run `email build`, it fails with the error message `Type error: An import path cannot end with a '.tsx' extension`. There is the same issue https://github.com/resendlabs/react-email/issues/657 but it is closed even it hasn't fixed now. So I opened a new issue for drawing attention.

### Which package is affected (leave empty if unsure)

client, react-email

### Link to the code that reproduces this issue

https://github.com/RanolP/react-email-cannot-build (same as react email starter)

### To Reproduce

```sh
# start here if you don't want to clone my repo
npx create-email
cd react-email-starter
# start here if you cloned the repo above
npm install
npx email build
```

and then it outputs

```
./emails/notion-magic-link.tsx:1:18
Type error: An import path cannot end with a '.tsx' extension. Consider importing '../../emails/notion-magic-link.js' instead.
```

### Expected Behavior

It should build preview page successfully.

### What's your node version? (if relevant)

Not relevant

**Comment by RanolP** [comment]
I think this issue can be solved in two ways:

1. Change the auto-generator code below

https://github.com/resendlabs/react-email/blob/bf92bd42b9fc8c05418ac10553924634378d8baf/packages/react-email/source/utils/generate-email-preview.ts#L82-L86

2. Upgrade client's typescript version to 5.x and use `allowImportingTsExtensions` option.

**Comment by RanolP** [comment]
I've done short investigation and the solution 1 cannot work and should go 2.

**Comment by shellscape** [comment]
Just ran into this. Turning on `allowImportingTsExtensions` is soooo dirty.

**Comment by RanolP** [comment]
I never realized that because the source code specified typescript version 5.1.6.

https://github.com/resendlabs/react-email/blob/490e0356685c1a6406c89620687725d0b98ad53b/client/package.json#L46

But due to the sync package operation, it could be overwritten to lower typescript version very easily. :sob:

https://github.com/resendlabs/react-email/blob/490e0356685c1a6406c89620687725d0b98ad53b/packages/react-email/source/utils/sync-package.ts#L6-L20

**Comment by shellscape** [comment]
yeah I noticed that 5.1.6 was in there. For some reason I'm getting 4.9.3 - and that version doesn't exist anywhere in my repo, except for .react-email.

I'm going to be working on a small utility to use some of the source in the repo here to build and output the templates without using this CLI. Will keep everyone posted.

**Comment by arnemolland** [comment]
> yeah I noticed that 5.1.6 was in there. For some reason I'm getting 4.9.3 - and that version doesn't exist anywhere in my repo, except for .react-email.
> 
> I'm going to be working on a small utility to use some of the source in the repo here to build and output the templates without using this CLI. Will keep everyone posted.

I guess that reason is the same why the downloaded template code is using _newer_ versions of e.g.`@radix-ui/react-tooltip` than the version used by the template package.json. It's breaking the types on my end and I have now idea why the CLI keeps downloading a package.json that's out of sync with the template code it downloads.

I had to solve this with some real gymnastics; two template tsconfig.json/package.json files, a chokidar script that watches for the creation of `.react-email/tsconfig.json|package.json` and swaps out the content before the CLI installs dependencies.

**Comment by vishnup-ditto** [comment]
Honestly, how is this not a bigger issue? Is nobody interested in building and deploying `react-email`? I currently use it mostly to create, export templates and manually send it out. I would like my preview web app deployed somewhere though.

**Comment by tomaszczura** [comment]
I am still getting that error on `1.10.0`

**Comment by RanolP** [comment]
I think they haven't yet released a newer version of `react-email-client`, tag push required. so embarrassing.
