### ISSUE TITLE
Typescript issue with React import in library

### ISSUE THREAD

**Issue by apetta** [resendlabs/react-email#885]
### Describe the Bug

The error
`../../../../node_modules/@react-email/section/dist/index.d.ts:1:24 - error TS7016: Could not find a declaration file for module 'react'. '/Users/.../node_modules/react/index.js' implicitly has an 'any' type.
  If the 'react' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react'
1 import * as React from 'react';` 
appears when using this library in a typescript node project.

### Link to the code that reproduces this issue

N/A

### To Reproduce

Use in a typescript node project with tsconfig.json:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "jsx": "react",
    "sourceMap": true,
    "strict": true,
    "target": "ES2022",
    "lib": ["ES2022", "DOM"],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "compileOnSave": true,
  "include": ["src", "src/emails"]
}
```

### Expected Behavior

Shouldn't be causing errors on import.

### What's your node version? (if relevant)

18.16.0

**Comment by lordelogos** [comment]
Hi @apetta,

From your error and `tsconfig` setup, I think I have an idea of the problem, to confirm this can you provide your **`package.json`**

You are most likely missing `@types/react` in your dev-dependencies, you can install it 
```sh
yarn add -D @types/react
```

Also you should really use  `ES6` or `ESNext` for the `module` field in your **_tsconfig_** except you have a specific use case
```
{
  "compilerOptions": {
    "module": "ES6",
    ...
  },
  ...
}
```

**Comment by apetta** [comment]
Hey! Thanks for the suggestion, it turns out that I had just forgotten to install the specific @react-email/section package 😅

**Comment by apetta** [comment]
> Hey! Thanks for the suggestion, it turns out that I had just forgotten to install the specific @react-email/section package 😅
