### ISSUE TITLE
React-Email cannot install behind corporate proxy

### ISSUE THREAD

**Issue by BStoller** [resendlabs/react-email#886]
### Describe the Bug

Installing react-email behind a proxy isn't available due to tree-node-cli's dependency on fast-folder size(1.6.0) - this version didn't support https_proxy environment variable and calls an HTTP service to get a DU service for windows hosts (which is what I am working on).

Could we remove the tree-node-cli dependency? If not, what other solutions could we use?

### Which package is affected (leave empty if unsure)

create-email

### Link to the code that reproduces this issue

https://github.com/resendlabs/react-email/blob/bf92bd42b9fc8c05418ac10553924634378d8baf/packages/react-email/source/commands/export.ts#L70-L73

### To Reproduce

https://github.com/resendlabs/react-email/blob/bf92bd42b9fc8c05418ac10553924634378d8baf/packages/create-email/src/index.js#L30-L34

https://github.com/resendlabs/react-email/blob/bf92bd42b9fc8c05418ac10553924634378d8baf/packages/react-email/source/commands/export.ts#L70-L73

### Expected Behavior

the package should be setup and available to begin developing emails.

**Comment by BStoller** [comment]
@zenorocha Thoughts?

**Comment by gabrielmfern** [comment]
> @zenorocha Thoughts?

Working on a fix for this along with some other common CLI bugs
