### ISSUE TITLE
calc() with + sign breaks tailwind

### ISSUE THREAD

**Issue by RanolP** [resendlabs/react-email#890]
### Describe the Bug

I used something like `max-h-[calc(50px+3rem)]` in my div and it silently ignored.

It is because those code doesn't pass + sign so it does not get cleaned their classname.

https://github.com/resendlabs/react-email/blob/490e0356685c1a6406c89620687725d0b98ad53b/packages/tailwind/src/tailwind.tsx#L116

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

https://github.com/RanolP/tailwind-calc-repro

### To Reproduce

Use calc() utilizing + sign anywhere in your tailwind class

### Expected Behavior

It should properly added

### What's your node version? (if relevant)

Not relevant

**Comment by gabrielmfern** [comment]
This should work now after #953. Upgrading to `@react-email/tailwind@0.0.11` should make it work.
