### ISSUE TITLE
Tailwind custom responsive screen not recognized when length of its name is not 2

### ISSUE THREAD

**Issue by RanolP** [resendlabs/react-email#891]
### Describe the Bug

If I declare a screen where the length of its name is not 2, it will be completely ignored.

because it filters based on the length not real screen name. see here

https://github.com/resendlabs/react-email/blob/490e0356685c1a6406c89620687725d0b98ad53b/packages/tailwind/src/tailwind.tsx#L90

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

https://github.com/RanolP/tailwind-breakpoint-repro

### To Reproduce

1. Declare screen where length of its name is not 2
2. Write responsive style
3. Totally get ignored

### Expected Behavior

It should not ignore configured screen names.

### What's your node version? (if relevant)

Not relevant

**Comment by gabrielmfern** [comment]
This should be closed due to #953, closing this, updating to `@react-email/tailwind@0.0.11` should solve it.
