### ISSUE TITLE
Resolve docs confusion between Section and Row

### ISSUE THREAD

**Issue by scrhartley** [resendlabs/react-email#897]
### Describe the Bug

It is unclear when to use Section and when to use Row. The docs are inconsistent and the examples don't help here.

- In the docs, Row is not listed as a component.
- The description for Section is "Display a section that can be formatted using columns.", but then the example does not use columns.
- In the examples, Column is used as a child of both Section and Row, e.g. https://github.com/resendlabs/react-email/blob/main/demo/emails/apple-receipt.tsx
- Following #872, the description and example of the Column says it must be used with a Row, in conflict with the other information.
- Implementation of Row and Section are almost identical, increasing the difficulty in distinguishing between the two.

Before #872, it seemed as if Section superseded Row and that Row was just historical and existed for compatibility. With this change, things are just more confusing.

### Link to the code that reproduces this issue

https://github.com/resendlabs/react-email

### To Reproduce

https://react.email/docs/components/column
https://react.email/docs/components/section
No Row in https://github.com/resendlabs/react-email/tree/main/docs/components

### Expected Behavior

Either:
- Row is de-emphasised
  - #872 is reverted
  - The examples are updated to not use Row
  - Section docs are updated to explain both its column and non-column usage, also possibly note that it replaces Row
- Row is a first-class component
  - Row is properly documented so that it's apparent it exists separately from Section
  - Section docs are updated to either not describe it as suitable for columns, or else explain that Row is also an option. Possibly also explain it's usage for centering content.
  - If Section _can_ also take columns, then update Column docs accordingly
  - Review the examples to ensure they are using Section and Row appropriately in accordance with the official guidance

**Comment by bukinoshita** [comment]
> In the docs, Row is not listed as a component.
The row was missing from the Docs, we just added.

> The description for Section is "Display a section that can be formatted using columns.", but then the example does not use columns.
This example was outdated and we just fixed.

> In the examples, Column is used as a child of both Section and Row, e.g.
Example app updated, the `Column` component should always be a children of a `Row`
