### ISSUE TITLE
Padding not getting applied properly

### ISSUE THREAD

**Issue by bhumit070** [resendlabs/react-email#902]
### Describe the Bug

I have setup react email in nextjs app router and trying with default dropbox email reset password template but in button padding is not getting applied while preview or rendering as html

### Link to the code that reproduces this issue

https://github.com/bhumit070/react-email-demo-app-dir

### To Reproduce

Just run pnpm run email:dev

### Expected Behavior

button should look exact same as. given in example

**Comment by lordelogos** [comment]
Hi @bhumit070,

To set padding to your button use the `pX` and `pY` props on the `Button` component.

In your case replace `padding: '14px 7px'` with the following
```tsx
<Button style={button} href={resetPasswordLink} pX={14} pY={7}>
```
There some optimisations in the `Button` component to make it render uniformly on most clients so it's best to use those props

**Comment by bhumit070** [comment]
Hey @lordelogos thanks for the solution it works but my issue is why it works in example but not in local
it creates some inconsistency.

**Comment by lordelogos** [comment]
You're absolutely correct on the inconsistency of the demo. I'll certainly investigate further.

If you don't have any additional concerns at the moment, could you please consider marking this as resolved for now?

Thank you for your understanding and cooperation.

**Comment by johanbook** [comment]
These properties are not mentioned in documentation https://react.email/docs/components/button. Have they been removed?

**Comment by lordelogos** [comment]
@johanbook yes they have.

You can apply padding with the `style` prop as normal now
