### ISSUE TITLE
Darkmode does not work with tailwind component

### ISSUE THREAD

**Issue by shahriyardx** [resendlabs/react-email#999]
### Describe the Bug

When using the tailwind component the darkmode works after sending the email but not in preview
I have tried to make my device dark also forcefully setting the color-scheme to dark using chrome's rendering settings

![image](https://github.com/resendlabs/react-email/assets/40076722/529c50cd-60e8-4c3f-8d40-8d491c8c6148)

The `dark:class` does not work in preview 

I have also added the head 
```jsx
<Head>
      <meta name="color-scheme" content="light dark" />
      <meta name="supported-color-schemes" content="light dark" />
 </Head>
````

### Which package is affected (leave empty if unsure)

@react-email/tailwind

### Link to the code that reproduces this issue

None

### To Reproduce

Just get create a text component and give it className 

```jsx
<Text className="text-white dark:text-black">Something</Text>
```

### Expected Behavior

The text should be dark on dark mode enabled or device dark mode

### What's your node version? (if relevant)

18.17.1

**Comment by gabrielmfern** [comment]
Thanks for opening up the issue! This seems to be an issue with the current tailwind package with media queries in general. I don't think that with the current setup they should work at all. Are you sure they are working when sending the email?

I am working on a fix for this right now as well.

**Comment by gabrielmfern** [comment]
> > Thanks for opening up the issue! This seems to be an issue with the current tailwind package with media queries in general. I don't think that with the current setup they should work at all. Are you sure they are working when sending the email?
> > I am working on a fix for this right now as well.
> 
> Yes after sending it works on mobile devices, I have tested on my Android Pixel 7 Pro -> Gmail App

Which version of the tailwind component are you using?

**Comment by shahriyardx** [comment]
> > > Thanks for opening up the issue! This seems to be an issue with the current tailwind package with media queries in general. I don't think that with the current setup they should work at all. Are you sure they are working when sending the email?
> > > I am working on a fix for this right now as well.
> > 
> > 
> > Yes after sending it works on mobile devices, I have tested on my Android Pixel 7 Pro -> Gmail App
> 
> Which version of the tailwind component are you using?

I was using old version, Upgraded to latest and checked still does not work in preview mode

**Comment by gabrielmfern** [comment]
> Which version of the tailwind component are you using?

So, only the canary version is working for you?

**Comment by gabrielmfern** [comment]
@shahriyardx we have a new canary version out that should have fixed this, can you test it out?

The version is `@react-email/tailwind@0.0.13-canary.0`

**Comment by Ehtisham-Ayaan** [comment]
I am not able to see any changes while giving dark color on gmail app

**Comment by gabrielmfern** [comment]
> I am not able to see any changes while giving dark color on gmail app

This seems to be an issue with Gmail itself, see https://www.caniemail.com/search/?s=media+queries.

**Comment by TYRANTHOSAURUS** [comment]
> > I am not able to see any changes while giving dark color on Gmail app
> 
> This seems to be an issue with Gmail itself, see https://www.caniemail.com/search/?s=media+queries.
> 
> Edit: on second thought, this might be because we are escaping the selectors, if this is the issue here, we already have a fix ready for it, just need to get it released

ETA on the release?

**Comment by domvillegas-ui** [comment]
Bumping this thread. Any ETA on a release? Thank you!

**Comment by JoshuaKirby88** [comment]
🤜

**Comment by gabrielmfern** [comment]
@domvillegas-ui @TYRANTHOSAURUS @JoshuaKirby88 has been out ever since [`@react-email/tailwind@0.0.15`](https://react.email/docs/changelog#mar-28-2024) recommend you all upgrade to `@react-emai/tailwind@1.0.4`/`@react-email/components@0.0.32`

**Comment by JoshuaKirby88** [comment]
Thanks!

Are there any recommendations to using css color variables that auto-resolve to the appropriate color based on the "dark" class, in React Email?

I think it's quite a common setup to define light and dark mode styles in a css file, and reference the variable in the tailwind config.
Further, load the css file inside the Head component, and wrap the Email template in the Tailwind component.

```css app/globals.css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
	:root {
		--background: 0 0% 100%;
	}
	.dark {
		--background: 240 10% 3.9%;
	}
}
```

```ts tailwind.config.ts
background: "hsl(var(--background))",
```

I'm currently doing:

```tsx email-components.tsx
export const MyTailwind = (props: { children: React.ReactNode }) => (
	<Tailwind config={{ darkMode: "media", theme: tailwindConfig.theme }}>
		{props.children}
	</Tailwind>
)
```

```tsx email-components.tsx
export const MyHead = () => {
	const globalStyles = readFileSync("app/globals.css", "utf8")

	return (
		<Head>
			<style>{globalStyles}</style>
			<meta name="color-scheme" content="light dark" />
		</Head>
	)
}
```

```tsx email-components.tsx
export const MyBody = (props: { children: React.ReactNode }) => (
	<Body>
		<div className="dark:hidden">{props.children}</div>
		<div className="dark hidden dark:block">{props.children}</div>
	</Body>
)
```

Which is not the best.

**Comment by gabrielmfern** [comment]
@JoshuaKirby88 I see what you're doing, but this is going to have really bad email client support because of the media query, the CSS variable itself. What I'd recommend is you make your email template normally for light mode, and try to adapt colors and other details so that the auto dark mode from email clients doesn't look as bad.

The CSS variables like this are common when we talk about web applications, but for email this is going to have really bad support, even if React Email allows it.

**Comment by JoshuaKirby88** [comment]
Right right okay.
That explains for the lack of resource on dark mode support for email.
I appreciate your quick response, thanks.
